package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Palette
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.ParameterMetadata

import org.wip.plugintoolkit.features.colorpicker.utils.toHex
import org.wip.plugintoolkit.features.colorpicker.utils.toRGB
import org.wip.plugintoolkit.shared.components.plugin.StandardTextField

@Composable
fun ColorInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false
) {
    var showColorPicker by remember { mutableStateOf(false) }
    val parsedColor = remember(value) { parseColorString(value) }
    val isArray = metadata.type is DataType.Array

    Column(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp)) {
        val inputLabel = @Composable {
            ParameterInputLabel(name, metadata, value, isAutoGenerated)
        }

        StandardTextField(
            value = value,
            onValueChange = onValueChange,
            readOnly = false,
            placeholder = if (isArray) "e.g. #FF0000, #00FF00" else "e.g. #FF0000 or rgb(255,0,0)",
            label = inputLabel,
            description = metadata.description,
            constraints = metadata.constraints,
            enabled = enabled,
            isRequired = metadata.required,
            type = metadata.type,
            trailingIcon = {
                if (!isArray) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Box(
                            modifier = Modifier
                                .size(24.dp)
                                .clip(RoundedCornerShape(4.dp))
                                .background(if (value.isEmpty() || parsedColor == Color.Transparent) Color.Transparent else parsedColor)
                                .border(1.dp, MaterialTheme.colorScheme.onSurface.copy(alpha = 0.2f), RoundedCornerShape(4.dp))
                        )
                        Spacer(modifier = Modifier.width(4.dp))
                        IconButton(
                            onClick = { showColorPicker = true },
                            enabled = enabled
                        ) {
                            Icon(
                                imageVector = Icons.Default.Palette,
                                contentDescription = "Pick color",
                                tint = MaterialTheme.colorScheme.primary
                            )
                        }
                    }
                }
            }
        )

        if (showColorPicker && enabled) {
            org.wip.plugintoolkit.features.colorpicker.ui.ColorPickerDialog(
                show = showColorPicker,
                onDismissRequest = { showColorPicker = false },
                
                onPickedColor = { color ->
                    showColorPicker = false
                    val formatted = if (metadata.semanticTypes.any {
                            it.canonicalId.contains("rgb", ignoreCase = true)
                        }
                    ) {
                        color.toRGB()
                    } else {
                        color.toHex()
                    }
                    onValueChange(formatted)
                }
            )
        }
    }
}

fun parseColorString(colorStr: String): Color {
    val trimmed = colorStr.trim()
    if (trimmed.isEmpty()) return Color.Transparent

    try {
        if (trimmed.startsWith("#")) {
            val hex = trimmed.substring(1)
            when (hex.length) {
                3 -> {
                    val r = hex[0].toString().repeat(2).toInt(16)
                    val g = hex[1].toString().repeat(2).toInt(16)
                    val b = hex[2].toString().repeat(2).toInt(16)
                    return Color(r, g, b, 255)
                }
                6 -> {
                    val r = hex.substring(0, 2).toInt(16)
                    val g = hex.substring(2, 4).toInt(16)
                    val b = hex.substring(4, 6).toInt(16)
                    return Color(r, g, b, 255)
                }
                8 -> {
                    val a = hex.substring(0, 2).toInt(16)
                    val r = hex.substring(2, 4).toInt(16)
                    val g = hex.substring(4, 6).toInt(16)
                    val b = hex.substring(6, 8).toInt(16)
                    return Color(r, g, b, a)
                }
            }
        }

        if (trimmed.startsWith("rgba", ignoreCase = true)) {
            val parts = trimmed.substringAfter("(").substringBefore(")").split(",").map { it.trim() }
            if (parts.size == 4) {
                return Color(
                    red = parts[0].toIntOrNull() ?: 0,
                    green = parts[1].toIntOrNull() ?: 0,
                    blue = parts[2].toIntOrNull() ?: 0,
                    alpha = ((parts[3].toFloatOrNull() ?: 1f) * 255).toInt()
                )
            }
        }

        if (trimmed.startsWith("rgb", ignoreCase = true)) {
            val parts = trimmed.substringAfter("(").substringBefore(")").split(",").map { it.trim() }
            if (parts.size == 3) {
                return Color(
                    red = parts[0].toIntOrNull() ?: 0,
                    green = parts[1].toIntOrNull() ?: 0,
                    blue = parts[2].toIntOrNull() ?: 0,
                    alpha = 255
                )
            }
        }

        return when (trimmed.lowercase()) {
            "black" -> Color.Black
            "white" -> Color.White
            "red" -> Color.Red
            "green" -> Color.Green
            "blue" -> Color.Blue
            "yellow" -> Color.Yellow
            "cyan" -> Color.Cyan
            "magenta" -> Color.Magenta
            "transparent" -> Color.Transparent
            "gray", "grey" -> Color.Gray
            "lightgray", "lightgrey" -> Color.LightGray
            "darkgray", "darkgrey" -> Color.DarkGray
            else -> Color.Transparent
        }
    } catch (e: Exception) {
        return Color.Transparent
    }
}
