package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import kotlinx.serialization.json.JsonElement
import org.jetbrains.compose.resources.stringResource
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.shared.components.settings.ExpressiveMenu
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.settings_enum_unlock_message
import org.wip.plugintoolkit.core.theme.ToolkitTheme
import plugintoolkit.composeapp.generated.resources.*

@Composable
fun EnumDropdownInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    providedLocks: Map<String, Boolean> = emptyMap(),
    compact: Boolean = false
) {
    Column(modifier = Modifier.fillMaxWidth().padding(vertical = if (compact) ToolkitTheme.spacing.none else ToolkitTheme.spacing.small)) {
        if (!compact) {
            val showTopLabel =
                metadata.description.isNotEmpty() || metadata.required || isAutoGenerated || metadata.semanticTypes.isNotEmpty()

            if (showTopLabel) {
                ParameterInputLabel(name, metadata, value, isAutoGenerated)

                if (metadata.description.isNotEmpty()) {
                    Text(
                        text = metadata.description,
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
                Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
            }
        }

        val enumType = metadata.type as? org.wip.plugintoolkit.api.DataType.Enum
        val options = enumType?.options ?: emptyList()
        val optionRequirements = enumType?.optionRequirements ?: emptyMap()
        val optionLockRequirements = enumType?.optionLockRequirements ?: emptyMap()

        val disabledOptions = options.filter { option ->
            val reqs = optionRequirements[option] ?: emptyList()
            val lockReqs = optionLockRequirements[option] ?: emptyList()

            val settingsSatisfied = reqs.all { reqSetting ->
                val reqValue = providedSettings[reqSetting]
                reqValue != null && reqValue.toString().replace("\"", "").isNotBlank()
            }
            val locksSatisfied = lockReqs.all { lockKey ->
                providedLocks[lockKey] == true
            }

            !settingsSatisfied || !locksSatisfied
        }.toSet()

        if (options.isNotEmpty()) {
            ExpressiveMenu<String>(
                options = options,
                selectedOption = if (value in options) value else (options.firstOrNull() ?: ""),
                onOptionSelected = { onValueChange(it) },
                labelProvider = { it },
                enabled = enabled,
                disabledOptions = disabledOptions
            )
            if (disabledOptions.size == options.size) {
                Text(
                    text = stringResource(Res.string.settings_enum_unlock_message),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(top = ToolkitTheme.spacing.extraSmall)
                )
            }
        } else {
            Text(stringResource(Res.string.common_no_options), color = MaterialTheme.colorScheme.error)
        }
    }
}
