package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.shared.components.settings.ExpressiveMenu

import kotlinx.serialization.json.JsonElement
import org.jetbrains.compose.resources.stringResource
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.settings_enum_unlock_message

@Composable
fun EnumDropdownInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    compact: Boolean = false
) {
    Column(modifier = Modifier.fillMaxWidth().padding(vertical = if (compact) 0.dp else 8.dp)) {
        if (!compact) {
            val showTopLabel =
                metadata.description.isNotEmpty() || metadata.required || isAutoGenerated || metadata.semanticTypes.isNotEmpty()

            if (showTopLabel) {
                ParameterInputLabel(name, metadata, value, isAutoGenerated)

                if (metadata.description.isNotEmpty()) {
                    Text(
                        text = metadata.description,
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
                Spacer(modifier = Modifier.height(8.dp))
            }
        }

        val enumType = metadata.type as? org.wip.plugintoolkit.api.DataType.Enum
        val options = enumType?.options ?: emptyList()
        val optionRequirements = enumType?.optionRequirements ?: emptyMap()

        val disabledOptions = options.filter { option ->
            val reqs = optionRequirements[option] ?: emptyList()
            // TODO: In the future we will want to have a custom validation function for optionally each setting,
            // this will be defined at the setting level, not where it is required though.
            !reqs.all { reqSetting ->
                val reqValue = providedSettings[reqSetting]
                reqValue != null && reqValue.toString().replace("\"", "").isNotBlank()
            }
        }.toSet()

        if (options.isNotEmpty()) {
            ExpressiveMenu<String>(
                options = options,
                selectedOption = if (value in options) value else (options.firstOrNull() ?: ""),
                onOptionSelected = { onValueChange(it) },
                labelProvider = { it },
                enabled = enabled,
                disabledOptions = disabledOptions
            )
            
            if (disabledOptions.size == options.size) {
                Text(
                    text = stringResource(Res.string.settings_enum_unlock_message),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(top = 4.dp)
                )
            }
        } else {
            Text("No options available", color = MaterialTheme.colorScheme.error)
        }
    }
}
