package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.shared.components.settings.ExpressiveMenu

@Composable
fun EnumDropdownInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false
) {
    Column(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp)) {
        val showTopLabel =
            metadata.description.isNotEmpty() || metadata.required || isAutoGenerated || metadata.semanticTypes.isNotEmpty()

        if (showTopLabel) {
            ParameterInputLabel(name, metadata, value, isAutoGenerated)

            if (metadata.description.isNotEmpty()) {
                Text(
                    text = metadata.description,
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }
            Spacer(modifier = Modifier.height(8.dp))
        }

        val options = (metadata.type as? org.wip.plugintoolkit.api.DataType.Enum)?.options ?: emptyList()

        if (options.isNotEmpty()) {
            ExpressiveMenu<String>(
                options = options,
                selectedOption = if (value in options) value else (options.firstOrNull() ?: ""),
                onOptionSelected = { onValueChange(it) },
                labelProvider = { it },
                enabled = enabled
            )
        } else {
            Text("No options available", color = MaterialTheme.colorScheme.error)
        }
    }
}
