package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Folder
import androidx.compose.material.icons.filled.FolderOpen
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.core.utils.PlatformUtils
import org.wip.plugintoolkit.core.utils.SemanticCategory
import org.koin.compose.koinInject
import org.wip.plugintoolkit.core.utils.SemanticRegistry
import org.wip.plugintoolkit.shared.components.plugin.StandardTextField

@Composable
fun FileInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    category: SemanticCategory,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false
) {
    val scope = rememberCoroutineScope()
    val semanticRegistry = koinInject<SemanticRegistry>()

    Column(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp)) {
        val inputLabel = @Composable {
            ParameterInputLabel(name, metadata, value, isAutoGenerated)
        }

        val isArray = metadata.type is DataType.Array
        val placeholderText = when (category) {
            SemanticCategory.IMAGE -> "No image selected"
            SemanticCategory.AUDIO -> "No audio selected"
            SemanticCategory.VIDEO -> "No video selected"
            SemanticCategory.PATH -> "No folder selected"
            else -> "No file selected"
        }

        StandardTextField(
            value = value,
            onValueChange = onValueChange,
            readOnly = false,
            placeholder = placeholderText,
            label = inputLabel,
            description = metadata.description,
            constraints = metadata.constraints,
            enabled = enabled,
            isRequired = metadata.required,
            type = metadata.type,
            trailingIcon = {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    if (value.isNotEmpty() && enabled) {
                        IconButton(onClick = { onValueChange("") }) {
                            Icon(
                                imageVector = Icons.Default.Close,
                                contentDescription = "Clear selection",
                                tint = MaterialTheme.colorScheme.error
                            )
                        }
                    }
                    IconButton(
                        onClick = {
                            scope.launch {
                                if (category == SemanticCategory.PATH) {
                                    val picked = PlatformUtils.pickFolder()
                                    if (picked != null) {
                                        val newValue = appendPickedValue(value, picked, isArray)
                                        onValueChange(newValue)
                                    }
                                } else {
                                    val allowedExtensions =
                                        semanticRegistry.getAllowedExtensions(metadata.semanticTypes)
                                    val picked = PlatformUtils.pickFile("Select File", allowedExtensions)
                                    if (picked != null) {
                                        val newValue = appendPickedValue(value, picked, isArray)
                                        onValueChange(newValue)
                                    }
                                }
                            }
                        },
                        enabled = enabled
                    ) {
                        Icon(
                            imageVector = if (category == SemanticCategory.PATH) Icons.Default.Folder else Icons.Default.FolderOpen,
                            contentDescription = if (category == SemanticCategory.PATH) "Browse folder" else "Browse file",
                            tint = MaterialTheme.colorScheme.primary
                        )
                    }
                }
            }
        )
    }
}

fun appendPickedValue(existingValue: String, newValue: String, isArray: Boolean): String {
    if (!isArray) return newValue
    if (existingValue.isBlank()) return newValue
    val existingList = existingValue.split(",").map { it.trim() }
    if (newValue in existingList) return existingValue
    return "$existingValue, $newValue"
}

fun getFileNames(path: String, isArray: Boolean): String {
    if (path.isEmpty()) return ""
    if (!isArray) return getFileName(path)
    return path.split(",").joinToString(", ") { getFileName(it.trim()) }
}

fun getFileName(path: String): String {
    return path.substringAfterLast("/").substringAfterLast("\\")
}
