package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.width
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.wip.plugintoolkit.api.ParameterMetadata

@Composable
fun ParameterInputLabel(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    isAutoGenerated: Boolean = false
) {
    Row(verticalAlignment = Alignment.CenterVertically) {
        Text(
            text = name,
            fontWeight = FontWeight.Bold,
            color = if (metadata.required && value.isEmpty()) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.onSurface
        )
        if (metadata.required) {
            Text(
                text = " *",
                color = MaterialTheme.colorScheme.error,
                fontWeight = FontWeight.Bold
            )
        }
        if (metadata.semanticTypes.isNotEmpty()) {
            Spacer(modifier = Modifier.width(4.dp))
            Text(
                text = "(${metadata.semanticTypes.joinToString { it.canonicalId }.uppercase()})",
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.7f)
            )
        }
        if (isAutoGenerated) {
            Spacer(modifier = Modifier.width(4.dp))
            Text(
                text = "(Auto-generated)",
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.7f)
            )
        }
    }
}
