package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.PrimitiveType
import org.wip.plugintoolkit.shared.components.plugin.StandardTextField

@Composable
fun PrimitiveInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false
) {
    val isArray = metadata.type is DataType.Array
    val baseType = if (isArray) (metadata.type as DataType.Array).items else metadata.type

    val inputLabel = @Composable {
        ParameterInputLabel(name, metadata, value, isAutoGenerated)
    }

    if (baseType is DataType.Primitive) {
        when (baseType.primitiveType) {
            PrimitiveType.BOOLEAN -> {
                if (isArray) {
                    StandardTextField(
                        value = value,
                        onValueChange = onValueChange,
                        readOnly = false,
                        placeholder = "e.g. true, false, true",
                        label = inputLabel,
                        description = metadata.description,
                        constraints = metadata.constraints,
                        enabled = enabled,
                        isRequired = metadata.required,
                        type = metadata.type,
                        isSecret = metadata.secret
                    )
                } else {
                    val boolValue = value.toBooleanStrictOrNull() ?: false
                    Column(modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            inputLabel()
                            Spacer(modifier = Modifier.weight(1f))
                            Switch(
                                checked = boolValue,
                                onCheckedChange = { onValueChange(it.toString()) },
                                enabled = enabled
                            )
                        }
                        if (metadata.description.isNotEmpty()) {
                            Text(
                                text = metadata.description,
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                }
            }

            PrimitiveType.INT, PrimitiveType.DOUBLE -> {
                val allowDecimal = baseType.primitiveType != PrimitiveType.INT
                val placeholderText = if (isArray) "e.g. 1, 2, 3" else if (allowDecimal) "e.g. 1.5" else "e.g. 42"

                // We handle input validation in StandardTextField or here
                // For simplicity, StandardTextField already supports Number inputs, but we can do a local filter.
                StandardTextField(
                    value = value,
                    onValueChange = { newValue ->
                        if (isArray) {
                            onValueChange(newValue)
                        } else {
                            if (newValue.isEmpty()) {
                                onValueChange("")
                            } else {
                                val validChars = newValue.all { it.isDigit() || it == '.' || it == '-' }
                                val hasDot = newValue.count { it == '.' } <= 1
                                val validMinus = newValue.indexOf('-') <= 0 && newValue.count { it == '-' } <= 1

                                val filtered = if (allowDecimal) {
                                    if (hasDot && validChars && validMinus) newValue else null
                                } else {
                                    if (validChars && validMinus && !newValue.contains('.')) newValue else null
                                }

                                if (filtered != null) {
                                    onValueChange(filtered)
                                }
                            }
                        }
                    },
                    readOnly = false,
                    placeholder = placeholderText,
                    label = inputLabel,
                    description = metadata.description,
                    constraints = metadata.constraints,
                    enabled = enabled,
                    isRequired = metadata.required,
                    type = metadata.type,
                    isSecret = metadata.secret,
                    keyboardOptions = androidx.compose.foundation.text.KeyboardOptions(keyboardType = if (allowDecimal) KeyboardType.Decimal else KeyboardType.Number)
                )
            }

            else -> {
                StandardTextField(
                    value = value,
                    onValueChange = onValueChange,
                    readOnly = false,
                    placeholder = if (isArray) "e.g. value1, value2" else "Enter ${name.lowercase()}",
                    label = inputLabel,
                    description = metadata.description,
                    constraints = metadata.constraints,
                    enabled = enabled,
                    isRequired = metadata.required,
                    type = metadata.type,
                    isSecret = metadata.secret
                )
            }
        }
    } else {
        StandardTextField(
            value = value,
            onValueChange = onValueChange,
            readOnly = false,
            placeholder = "Enter ${name.lowercase()}",
            label = inputLabel,
            description = metadata.description,
            constraints = metadata.constraints,
            enabled = enabled,
            isRequired = metadata.required,
            type = metadata.type,
            isSecret = metadata.secret
        )
    }
}
