package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import kotlinx.serialization.json.JsonElement
import org.jetbrains.compose.resources.stringResource
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.core.theme.ToolkitTheme
import org.wip.plugintoolkit.features.plugin.logic.PluginManager
import org.wip.plugintoolkit.features.plugin.utils.CapabilityLockUtils
import org.wip.plugintoolkit.shared.components.settings.ExpressiveMenu
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.common_no_options
import plugintoolkit.composeapp.generated.resources.settings_enum_unlock_message

@Composable
fun EnumDropdownInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    providedLocks: Map<String, Boolean> = emptyMap(),
    compact: Boolean = false,
    hasUnsavedChanges: Boolean = false,
    pluginId: String = "",
    onNavigateToPluginSetting: ((pluginId: String, settingKey: String) -> Unit)? = null
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = if (compact) ToolkitTheme.spacing.none else ToolkitTheme.spacing.small)
    ) {
        if (!compact) {
            val showTopLabel =
                metadata.description.isNotEmpty() || metadata.required || isAutoGenerated || metadata.semanticTypes.isNotEmpty()

            if (showTopLabel) {
                ParameterInputLabel(name, metadata, value, isAutoGenerated)

                if (metadata.description.isNotEmpty()) {
                    Text(
                        text = metadata.description,
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
                Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
            }
        }

        val enumType = metadata.type as? org.wip.plugintoolkit.api.DataType.Enum
        val options = enumType?.options ?: emptyList()
        val optionRequirements = enumType?.optionRequirements ?: emptyMap()
        val optionLockRequirements = enumType?.optionLockRequirements ?: emptyMap()

        val disabledOptions = options.filter { option ->
            val reqs = optionRequirements[option] ?: emptyList()
            val lockReqs = optionLockRequirements[option] ?: emptyList()

            val settingsSatisfied = reqs.all { reqSetting ->
                val reqValue = providedSettings[reqSetting]
                reqValue != null && reqValue.toString().replace("\"", "").isNotBlank()
            }
            val locksSatisfied = lockReqs.all { lockKey ->
                CapabilityLockUtils.isLockSatisfied(lockKey, providedLocks)
            }

            !settingsSatisfied || !locksSatisfied
        }.toSet()

        // Provide per-option setting key for deep-link navigation (settings → unlock option)
        val optionTargetSettingKey: (String) -> String = { option ->
            optionRequirements[option]?.firstOrNull()
                ?: optionLockRequirements[option]?.firstOrNull()
                ?: ""
        }

        // Fallback key used by the visual hint text below the dropdown
        val firstRequiredSettingKey = options.firstNotNullOfOrNull { option ->
            optionRequirements[option]?.firstOrNull() ?: optionLockRequirements[option]?.firstOrNull()
        } ?: ""

        val effectivePluginId = if (pluginId.isNotBlank()) pluginId else remember {
            org.koin.core.context.GlobalContext.getOrNull()?.get<PluginManager>()?.loadedPlugins?.value?.firstOrNull() ?: ""
        }

        if (options.isNotEmpty()) {
            val effectiveSelected = if (value in options) value else (options.firstOrNull() ?: "")
            LaunchedEffect(effectiveSelected) {
                if (value !in options && effectiveSelected.isNotBlank()) {
                    onValueChange(effectiveSelected)
                }
            }

            ExpressiveMenu<String>(
                options = options,
                selectedOption = effectiveSelected,
                onOptionSelected = { onValueChange(it) },
                labelProvider = { it },
                enabled = enabled,
                disabledOptions = disabledOptions,
                disabledOptionTargetKey = optionTargetSettingKey,
                hasUnsavedChanges = hasUnsavedChanges,
                pluginId = effectivePluginId,
                onNavigateToPluginSetting = onNavigateToPluginSetting
            )
            if (disabledOptions.isNotEmpty()) {
                // TODO: This visual hint is now redundant as a tap target (interception moved to individual
                //       DropdownMenuItems above). Consider removing or updating this text in a future cleanup.
                Text(
                    text = stringResource(Res.string.settings_enum_unlock_message),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(top = ToolkitTheme.spacing.extraSmall)
                )
            }
        } else {
            Text(stringResource(Res.string.common_no_options), color = MaterialTheme.colorScheme.error)
        }
    }
}
