package org.wip.plugintoolkit.shared.components.plugin.inputs

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Folder
import androidx.compose.material.icons.filled.FolderOpen
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import kotlinx.coroutines.launch
import org.koin.compose.koinInject
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.SemanticType
import org.wip.plugintoolkit.core.utils.PlatformUtils
import org.wip.plugintoolkit.core.utils.SemanticCategory
import org.wip.plugintoolkit.core.utils.SemanticRegistry
import org.wip.plugintoolkit.shared.components.plugin.StandardTextField
import org.wip.plugintoolkit.core.theme.ToolkitTheme
import org.jetbrains.compose.resources.stringResource
import plugintoolkit.composeapp.generated.resources.*

@Composable
fun FileInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    category: SemanticCategory,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false,
    compact: Boolean = false,
    customExtensions: List<String>? = null
) {
    val scope = rememberCoroutineScope()
    val semanticRegistry = koinInject<SemanticRegistry>()

    Column(modifier = Modifier.fillMaxWidth().padding(vertical = if (compact) ToolkitTheme.spacing.none else ToolkitTheme.spacing.small)) {
        val inputLabel: @Composable () -> Unit = {
            if (!compact) {
                ParameterInputLabel(name, metadata, value, isAutoGenerated)
            }
        }

        val isArray = metadata.type is DataType.Array
        val placeholderText = when (category) {
            SemanticCategory.IMAGE -> stringResource(Res.string.input_no_image_selected)
            SemanticCategory.AUDIO -> stringResource(Res.string.input_no_audio_selected)
            SemanticCategory.VIDEO -> stringResource(Res.string.input_no_video_selected)
            SemanticCategory.PATH -> stringResource(Res.string.input_no_folder_selected)
            else -> stringResource(Res.string.input_no_file_selected)
        }

        val allowedExtensions = remember(customExtensions, metadata.semanticTypes) {
            computeAllowedExtensions(metadata.semanticTypes, customExtensions, semanticRegistry)
        }

        val extensionError = remember(value, allowedExtensions, customExtensions, isArray) {
            if (category != SemanticCategory.PATH && value.isNotBlank()) {
                val rawCustom = customExtensions?.map { it.trim().lowercase() }?.filter { it.isNotEmpty() } ?: emptyList()
                val negated = rawCustom.filter { it.startsWith("!") }.map { it.removePrefix("!").removePrefix(".") }
                val paths = if (isArray) value.split(",").map { it.trim() }.filter { it.isNotEmpty() } else listOf(value)
                val invalid = paths.filterNot { isExtensionValid(it, allowedExtensions, negated) }
                if (invalid.isNotEmpty()) {
                    if (allowedExtensions.isNotEmpty()) {
                        allowedExtensions.joinToString(", ")
                    } else if (negated.isNotEmpty()) {
                        "not ${negated.joinToString(", ")}"
                    } else null
                } else null
            } else null
        }
        val customErrorMessage = extensionError?.let { stringResource(Res.string.input_unsupported_extension, it) }

        val browseFileTitle = stringResource(Res.string.action_browse_file)
        val launchPicker: () -> Unit = {
            scope.launch {
                if (category == SemanticCategory.PATH) {
                    val picked = PlatformUtils.pickFolder()
                    if (picked != null) {
                        val newValue = appendPickedValue(value, picked, isArray)
                        onValueChange(newValue)
                    }
                } else {
                    val picked = PlatformUtils.pickFile(browseFileTitle, allowedExtensions)
                    if (picked != null) {
                        val newValue = appendPickedValue(value, picked, isArray)
                        onValueChange(newValue)
                    }
                }
            }
        }

        val browseIcon = if (category == SemanticCategory.PATH) Icons.Default.Folder else Icons.Default.FolderOpen
        val browseContentDesc = if (category == SemanticCategory.PATH) {
            stringResource(Res.string.action_browse_folder)
        } else {
            stringResource(Res.string.action_browse_file)
        }

        StandardTextField(
            value = value,
            onValueChange = onValueChange,
            readOnly = false,
            placeholder = placeholderText,
            label = inputLabel,
            description = if (compact) "" else metadata.description,
            constraints = metadata.constraints,
            enabled = enabled,
            isRequired = metadata.required,
            isAutoGenerated = isAutoGenerated,
            type = metadata.type,
            compact = compact,
            customErrorMessage = customErrorMessage,
            trailingIcon = {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    if (value.isNotEmpty() && enabled) {
                        if (compact) {
                            Box(
                                modifier = Modifier
                                    .size(ToolkitTheme.dimensions.iconMediumLarge)
                                    .clickable(enabled = enabled) { onValueChange("") },
                                contentAlignment = Alignment.Center
                            ) {
                                Icon(
                                    imageVector = Icons.Default.Close,
                                    contentDescription = stringResource(Res.string.action_clear_selection),
                                    tint = MaterialTheme.colorScheme.error,
                                    modifier = Modifier.size(ToolkitTheme.dimensions.iconExtraSmall)
                                )
                            }
                        } else {
                            IconButton(onClick = { onValueChange("") }) {
                                Icon(
                                    imageVector = Icons.Default.Close,
                                    contentDescription = stringResource(Res.string.action_clear_selection),
                                    tint = MaterialTheme.colorScheme.error
                                )
                            }
                        }
                    }
                    if (compact) {
                        Box(
                            modifier = Modifier
                                .size(ToolkitTheme.dimensions.iconMediumLarge)
                                .clickable(enabled = enabled) { launchPicker() },
                            contentAlignment = Alignment.Center
                        ) {
                            Icon(
                                imageVector = browseIcon,
                                contentDescription = browseContentDesc,
                                tint = MaterialTheme.colorScheme.primary,
                                modifier = Modifier.size(ToolkitTheme.dimensions.iconExtraSmall)
                            )
                        }
                    } else {
                        IconButton(
                            onClick = launchPicker,
                            enabled = enabled
                        ) {
                            Icon(
                                imageVector = browseIcon,
                                contentDescription = browseContentDesc,
                                tint = MaterialTheme.colorScheme.primary
                            )
                        }
                    }
                }
            }
        )
    }
}

fun computeAllowedExtensions(
    semanticTypes: List<SemanticType>,
    customExtensions: List<String>?,
    semanticRegistry: SemanticRegistry
): List<String> {
    val semanticExts = semanticRegistry.getAllowedExtensions(semanticTypes)
    val rawCustom = customExtensions?.map { it.trim().lowercase() }?.filter { it.isNotEmpty() } ?: emptyList()
    val negated = rawCustom.filter { it.startsWith("!") }.map { it.removePrefix("!").removePrefix(".") }
    val positive = rawCustom.filter { !it.startsWith("!") }.map { it.removePrefix(".") }
    val base = if (positive.isNotEmpty()) positive else semanticExts
    return base.filter { it !in negated }.distinct()
}

fun isExtensionValid(
    filePath: String,
    allowedExtensions: List<String>,
    negatedExtensions: List<String> = emptyList()
): Boolean {
    if (filePath.isBlank()) return true
    val filename = filePath.substringAfterLast('/').substringAfterLast('\\')
    val ext = if (filename.contains('.')) filename.substringAfterLast('.').lowercase() else ""
    if (ext.isNotEmpty() && ext in negatedExtensions) return false
    if (allowedExtensions.isNotEmpty()) {
        return ext.isNotEmpty() && ext in allowedExtensions
    }
    return true
}

fun appendPickedValue(existingValue: String, newValue: String, isArray: Boolean): String {
    if (!isArray) return newValue
    if (existingValue.isBlank()) return newValue
    val existingList = existingValue.split(",").map { it.trim() }
    if (newValue in existingList) return existingValue
    return "$existingValue, $newValue"
}

fun getFileNames(path: String, isArray: Boolean): String {
    if (path.isEmpty()) return ""
    if (!isArray) return getFileName(path)
    return path.split(",").joinToString(", ") { getFileName(it.trim()) }
}

fun getFileName(path: String): String {
    return path.substringAfterLast("/").substringAfterLast("\\")
}
