package org.wip.plugintoolkit.features.job.logic

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonPrimitive
import org.wip.plugintoolkit.api.Capability
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.FileAccess
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.PluginInfo
import org.wip.plugintoolkit.api.PluginManifest
import org.wip.plugintoolkit.api.PrimitiveType
import org.wip.plugintoolkit.api.Requirements
import org.wip.plugintoolkit.api.SemanticType
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class JobWorkerUtilsTest {

    private fun createMockManifest(
        capabilities: List<Capability>
    ): PluginManifest {
        return PluginManifest(
            manifestVersion = "1.0",
            plugin = PluginInfo("test", "Test Plugin", "1.0", "Author"),
            requirements = Requirements(minMemoryMb = 100, minExecutionTimeMs = 100),
            capabilities = capabilities,
            settings = emptyMap(),
            actions = emptyList()
        )
    }

    @Test
    fun testResolveFileAccess_AllowedPathsExtraction() {
        val cap = Capability(
            name = "testCap",
            description = "Test",
            returnType = DataType.Primitive(PrimitiveType.UNIT),
            parameters = mapOf(
                "inFile" to ParameterMetadata(
                    description = "Input File",
                    type = DataType.Primitive(PrimitiveType.STRING),
                    semanticTypes = listOf(SemanticType("file", "input", null))
                ),
                "normalParam" to ParameterMetadata(
                    description = "Normal Param",
                    type = DataType.Primitive(PrimitiveType.STRING)
                )
            )
        )
        val manifest = createMockManifest(listOf(cap))
        
        val parameters = mutableMapOf<String, JsonElement>(
            "inFile" to JsonPrimitive("/safe/path/file.txt"),
            "normalParam" to JsonPrimitive("just text")
        )

        val (allowedPaths, isDestructive) = resolveFileAccess(manifest, "testCap", parameters)

        assertEquals(1, allowedPaths.size)
        assertEquals("/safe/path/file.txt", allowedPaths[0])
        assertFalse(isDestructive)
    }

    @Test
    fun testResolveFileAccess_AutoRouteToSandbox() {
        val cap = Capability(
            name = "processData",
            description = "Test",
            returnType = DataType.Primitive(PrimitiveType.UNIT),
            parameters = mapOf(
                "outFile" to ParameterMetadata(
                    description = "Output File",
                    type = DataType.Primitive(PrimitiveType.STRING),
                    semanticTypes = listOf(SemanticType("file", "output", null))
                )
            ),
            fileAccess = FileAccess(writesFiles = true)
        )
        val manifest = createMockManifest(listOf(cap))
        
        val parameters = mutableMapOf<String, JsonElement>() // Empty parameters!

        val sandboxPath = "/appData/jobs/123/sandbox/node_1"
        val normalizedSandboxPath = kotlinx.io.files.Path(sandboxPath).toString()
        val (allowedPaths, _) = resolveFileAccess(manifest, "processData", parameters, sandboxPath)

        // It should have generated a path in the sandbox
        val generatedPath = parameters["outFile"]?.let { if (it is JsonPrimitive) it.content else null }
        assertTrue(generatedPath != null)
        assertTrue(generatedPath.startsWith(normalizedSandboxPath))
        assertTrue(generatedPath.endsWith(".tmp"))

        // And it should have added it to allowedPaths
        assertEquals(1, allowedPaths.size)
        assertEquals(generatedPath, allowedPaths[0])
    }

    @Test
    fun testResolveFileAccess_IsDestructive() {
        val cap = Capability(
            name = "deleteData",
            description = "Test",
            returnType = DataType.Primitive(PrimitiveType.UNIT),
            parameters = emptyMap(),
            fileAccess = FileAccess(isDestructive = true)
        )
        val manifest = createMockManifest(listOf(cap))
        
        val parameters = mutableMapOf<String, JsonElement>()

        val (_, isDestructive) = resolveFileAccess(manifest, "deleteData", parameters)

        assertTrue(isDestructive)
    }

    @Test
    fun testResolveFileAccess_AutogeneratedPattern() {
        val cap = Capability(
            name = "processData",
            description = "Test",
            returnType = DataType.Primitive(PrimitiveType.UNIT),
            parameters = mapOf(
                "inputPath" to ParameterMetadata(
                    description = "Input File",
                    type = DataType.Primitive(PrimitiveType.STRING),
                    semanticTypes = listOf(SemanticType("file", "input", null))
                ),
                "outputPath" to ParameterMetadata(
                    description = "Output File",
                    type = DataType.Primitive(PrimitiveType.STRING),
                    semanticTypes = listOf(SemanticType("file", "output", null)),
                    autogeneratedPattern = "{inputPath}/../../out.txt"
                )
            ),
            fileAccess = FileAccess(writesFiles = true)
        )
        val manifest = createMockManifest(listOf(cap))
        
        val parameters = mutableMapOf<String, JsonElement>(
            "inputPath" to JsonPrimitive("/test/folder/input.txt")
        )

        val (allowedPaths, _) = resolveFileAccess(manifest, "processData", parameters)

        val generatedPath = parameters["outputPath"]?.let { if (it is JsonPrimitive) it.content else null }
        assertEquals("/test/folder/input.txt/../../out.txt", generatedPath)
        assertTrue(allowedPaths.contains("/test/folder/input.txt/../../out.txt"))
        assertTrue(allowedPaths.contains("/test/folder/input.txt"))
    }
}
