package org.wip.plugintoolkit.features.plugin.viewmodel

import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.slot
import io.mockk.unmockkAll
import io.mockk.verify
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import kotlinx.serialization.json.JsonPrimitive
import org.wip.plugintoolkit.api.Capability
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.PluginEntry
import org.wip.plugintoolkit.api.PluginInfo
import org.wip.plugintoolkit.api.PluginManifest
import org.wip.plugintoolkit.api.PrimitiveType
import org.wip.plugintoolkit.api.Requirements
import org.wip.plugintoolkit.core.notification.NotificationService
import org.wip.plugintoolkit.features.job.logic.JobManager
import org.wip.plugintoolkit.features.job.model.BackgroundJob
import org.wip.plugintoolkit.features.job.model.JobProgress
import org.wip.plugintoolkit.features.job.model.JobStatus
import org.wip.plugintoolkit.features.job.model.JobType
import org.wip.plugintoolkit.features.plugin.logic.PluginManager
import org.wip.plugintoolkit.features.plugin.model.InstalledPlugin
import org.wip.plugintoolkit.features.plugin.model.PluginSettingsStore
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

@OptIn(ExperimentalCoroutinesApi::class)
class SinglePluginHostViewModelTest {

    private val testDispatcher = StandardTestDispatcher()
    private val pluginEntry = mockk<PluginEntry>()
    private val jobManager = mockk<JobManager>(relaxed = true)
    private val notificationService = mockk<NotificationService>(relaxed = true)
    private val pluginManager = mockk<PluginManager>(relaxed = true)

    private val jobsFlow = MutableStateFlow<List<BackgroundJob>>(emptyList())
    private val endedJobsFlow = MutableStateFlow<List<BackgroundJob>>(emptyList())
    private val jobProgressFlow = MutableStateFlow<Map<String, JobProgress>>(emptyMap())
    private val jobLogsFlow = MutableStateFlow<Map<String, List<String>>>(emptyMap())
    private val installedPluginsFlow = MutableStateFlow<List<InstalledPlugin>>(emptyList())
    private val pluginLocksStateFlow = MutableStateFlow<Map<String, Map<String, Boolean>>>(emptyMap())
    private val pluginSettingsStateFlow = MutableStateFlow<Map<String, PluginSettingsStore>>(emptyMap())

    private val capability1 = Capability(
        name = "compress",
        description = "Compress an image file",
        parameters = mapOf(
            "inputPath" to ParameterMetadata(
                defaultValue = JsonPrimitive("/path/to/image.png"),
                description = "Path to input file",
                type = DataType.Primitive(PrimitiveType.STRING)
            ),
            "outputPath" to ParameterMetadata(
                defaultValue = null,
                description = "Path to output file",
                type = DataType.Primitive(PrimitiveType.STRING),
                autogeneratedPattern = "{inputPath}_out.jpg"
            ),
            "quality" to ParameterMetadata(
                defaultValue = JsonPrimitive("85"),
                description = "Compression quality",
                type = DataType.Primitive(PrimitiveType.STRING)
            )
        ),
        returnType = DataType.Primitive(PrimitiveType.STRING),
        isPausable = true,
        isCancellable = true
    )

    private val capability2 = Capability(
        name = "resize",
        description = "Resize an image file",
        parameters = mapOf(
            "scale" to ParameterMetadata(
                defaultValue = JsonPrimitive("0.5"),
                description = "Scale factor",
                type = DataType.Primitive(PrimitiveType.STRING)
            )
        ),
        returnType = DataType.Primitive(PrimitiveType.STRING),
        isPausable = false,
        isCancellable = true
    )

    private val testManifest = PluginManifest(
        manifestVersion = "1.0",
        plugin = PluginInfo(
            id = "org.test.plugin",
            name = "Test Plugin",
            version = "1.0.0",
            description = "Test plugin description"
        ),
        requirements = Requirements(
            minMemoryMb = 256,
            minExecutionTimeMs = 100
        ),
        capabilities = listOf(capability1, capability2),
        hasSetupHandler = true
    )

    @BeforeTest
    fun setUp() {
        Dispatchers.setMain(testDispatcher)
        every { pluginEntry.getManifest() } returns Result.success(testManifest)
        every { jobManager.jobs } returns jobsFlow
        every { jobManager.endedJobs } returns endedJobsFlow
        every { jobManager.jobProgress } returns jobProgressFlow
        every { jobManager.jobLogs } returns jobLogsFlow
        every { pluginManager.installedPlugins } returns installedPluginsFlow
        every { pluginManager.pluginLocksState } returns pluginLocksStateFlow
        every { pluginManager.pluginSettingsState } returns pluginSettingsStateFlow
        every { pluginManager.loadPluginSettings("org.test.plugin") } returns PluginSettingsStore()
    }

    @AfterTest
    fun tearDown() {
        Dispatchers.resetMain()
        unmockkAll()
    }

    private fun createViewModel(): SinglePluginHostViewModel {
        return SinglePluginHostViewModel(
            pluginEntry = pluginEntry,
            jobManager = jobManager,
            notificationService = notificationService,
            pluginManager = pluginManager
        )
    }

    @Test
    fun testInitialStateLoadsManifestAndFirstCapability() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        assertEquals("org.test.plugin", viewModel.pluginId)
        assertEquals(2, viewModel.capabilities.size)
        assertTrue(viewModel.hasSetupHandler)
        assertEquals(capability1, viewModel.selectedCapability)

        // Verify default parameters loaded
        assertEquals("/path/to/image.png", viewModel.parameterValues["inputPath"])
        assertEquals("85", viewModel.parameterValues["quality"])
        // Verify autogenerated pattern evaluated
        assertEquals("/path/to/image.png_out.jpg", viewModel.parameterValues["outputPath"])
    }

    @Test
    fun testSelectCapabilitySwitchesParameters() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        viewModel.selectCapability(capability2)
        advanceUntilIdle()

        assertEquals(capability2, viewModel.selectedCapability)
        assertEquals("0.5", viewModel.parameterValues["scale"])
        assertNull(viewModel.parameterValues["inputPath"])
        assertNull(viewModel.parameterValues["quality"])

        viewModel.selectCapability(null)
        assertNull(viewModel.selectedCapability)
        assertTrue(viewModel.parameterValues.isEmpty())
    }

    @Test
    fun testUpdateParameterUpdatesValueAndAutogeneratedPattern() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        viewModel.updateParameter("inputPath", "/photos/sunset.png")

        assertEquals("/photos/sunset.png", viewModel.parameterValues["inputPath"])
        assertEquals("/photos/sunset.png_out.jpg", viewModel.parameterValues["outputPath"])
        assertTrue(viewModel.isParameterAutoGenerated("outputPath"))
    }

    @Test
    fun testManualOverrideOfAutogeneratedParameterPreventsAutoEvaluation() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        // Manually override outputPath
        viewModel.updateParameter("outputPath", "/custom/destination.png")
        assertFalse(viewModel.isParameterAutoGenerated("outputPath"))

        // Update inputPath dependency - outputPath should NOT change
        viewModel.updateParameter("inputPath", "/photos/landscape.png")
        assertEquals("/custom/destination.png", viewModel.parameterValues["outputPath"])

        // Clear manual override - should re-enable autogeneration
        viewModel.updateParameter("outputPath", "")
        assertEquals("/photos/landscape.png_out.jpg", viewModel.parameterValues["outputPath"])
        assertTrue(viewModel.isParameterAutoGenerated("outputPath"))
    }

    @Test
    fun testExecuteCapabilityEnqueuesJob() = runTest(testDispatcher) {
        installedPluginsFlow.value = listOf(
            InstalledPlugin(
                pkg = "org.test.plugin",
                name = "Test Plugin",
                version = "1.0.0",
                installPath = "/tmp",
                isSetupCompleted = true
            )
        )
        val viewModel = createViewModel()
        advanceUntilIdle()

        val jobSlot = slot<BackgroundJob>()
        every { jobManager.enqueueJob(capture(jobSlot)) } returns Unit

        viewModel.executeCapability()
        advanceUntilIdle()

        assertTrue(jobSlot.isCaptured)
        val captured = jobSlot.captured
        assertEquals("org.test.plugin", captured.pluginId)
        assertEquals("compress", captured.capabilityName)
        assertEquals(JobType.Capability, captured.type)
        assertTrue(captured.keepResult)
        assertTrue(captured.isPausable)
        assertTrue(captured.isCancellable)
        assertEquals(JsonPrimitive("/path/to/image.png"), captured.parameters["inputPath"])
        assertEquals(JsonPrimitive("85"), captured.parameters["quality"])
        verify { notificationService.toast("Executing compress in background") }
    }

    @Test
    fun testExecuteCapabilityBlockedWhenSetupNotCompleted() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        assertFalse(viewModel.isPluginReady.value)

        viewModel.executeCapability()
        advanceUntilIdle()

        verify(exactly = 0) { jobManager.enqueueJob(any()) }
        verify { notificationService.toast("Plugin setup is required before executing capabilities") }
    }

    @Test
    fun testRunSetupEnqueuesSetupJob() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        viewModel.runSetup()
        advanceUntilIdle()

        coVerify { pluginManager.enqueueSetupJob("org.test.plugin") }
        verify { notificationService.toast("Starting setup for Test Plugin...") }
    }

    @Test
    fun testJobControlMethodsDelegateToJobManager() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        viewModel.cancelJob("job_01", force = true)
        advanceUntilIdle()
        coVerify { jobManager.cancelJob("job_01", true) }

        viewModel.pauseJob("job_01")
        advanceUntilIdle()
        coVerify { jobManager.pauseJob("job_01") }

        viewModel.resumeJob("job_01")
        advanceUntilIdle()
        coVerify { jobManager.resumeJob("job_01") }

        viewModel.removeEndedJob("job_01")
        verify { jobManager.clearEndedJob("job_01") }
    }

    @Test
    fun testClearCapabilityHistory() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        viewModel.clearCapabilityHistory()
        verify { jobManager.removeJobs(any<(BackgroundJob) -> Boolean>()) }
    }

    @Test
    fun testResetParametersToDefault() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        viewModel.updateParameter("quality", "20")
        assertEquals("20", viewModel.parameterValues["quality"])

        viewModel.resetParametersToDefault()
        assertEquals("85", viewModel.parameterValues["quality"])
    }

    @Test
    fun testSaveCurrentParametersAsDefault() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        viewModel.updateParameter("quality", "95")
        viewModel.saveCurrentParametersAsDefault()

        verify { pluginManager.savePluginSettings("org.test.plugin", any<PluginSettingsStore>()) }
        verify { notificationService.toast(any<String>()) }
    }

    @Test
    fun testSetupStateTracking() = runTest(testDispatcher) {
        val viewModel = createViewModel()
        advanceUntilIdle()

        assertFalse(viewModel.isSetupRunning.value)
        assertFalse(viewModel.isSetupCompleted.value)

        // Simulate setup job running
        val runningJob = BackgroundJob(
            id = "setup_1",
            name = "Setup",
            type = JobType.Setup,
            pluginId = "org.test.plugin",
            capabilityName = "setup",
            status = JobStatus.Running
        )
        jobsFlow.value = listOf(runningJob)
        advanceUntilIdle()

        assertTrue(viewModel.isSetupRunning.value)

        // Simulate setup job completed
        jobsFlow.value = emptyList()
        val completedJob = runningJob.copy(status = JobStatus.Completed)
        endedJobsFlow.value = listOf(completedJob)
        advanceUntilIdle()

        assertFalse(viewModel.isSetupRunning.value)
        assertTrue(viewModel.isSetupCompleted.value)
    }
}
