package org.wip.plugintoolkit.features

import kotlinx.serialization.json.Json
import org.wip.plugintoolkit.api.PluginManifest
import java.io.File
import java.util.zip.ZipFile
import kotlin.test.Test

class ManifestTest {
    @Test
    fun testJarManifest() {
        val jarFile = File("../completeExample/build/libs/completeExample.jar")
        if (!jarFile.exists()) return
        val zip = ZipFile(jarFile)
        val entry = zip.getEntry("META-INF/manifest.json")
        val manifestString = zip.getInputStream(entry).reader().readText()

        val format = Json { ignoreUnknownKeys = true }
        val manifest = format.decodeFromString<PluginManifest>(manifestString)

        val capability = manifest.capabilities.find { it.name == "capabilityWithFileAccess" }
        println("capabilityWithFileAccess fileAccess: ${capability?.fileAccess}")
        val outputPath = capability?.parameters?.get("outputPath")
        println("outputPath autogeneratedPattern: ${outputPath?.autogeneratedPattern}")
    }
}
