package org.wip.plugintoolkit.features

import kotlinx.serialization.json.Json
import org.wip.plugintoolkit.api.PluginManifest
import java.io.File
import java.util.zip.ZipFile
import kotlin.test.Test

class ManifestTest {
    @Test
    fun testJarManifest() {
        val jarFile = File("../operations/build/libs/operations.jar")
        val zip = ZipFile(jarFile)
        val entry = zip.getEntry("META-INF/manifest.json")
        val manifestString = zip.getInputStream(entry).reader().readText()

        val format = Json { ignoreUnknownKeys = true }
        val manifest = format.decodeFromString<PluginManifest>(manifestString)

        val batch = manifest.capabilities.find { it.name == "batch_process" }
        println("batch_process fileAccess: ${batch?.fileAccess}")
        val outA = batch?.parameters?.get("outputA")
        println("outputA autogeneratedPattern: ${outA?.autogeneratedPattern}")
    }
}
