package org.wip.plugintoolkit.features.flows.logic

import kotlinx.io.files.Path

/**
 * Utility class to evaluate and resolve autogenerated path patterns for node outputs.
 * 
 * IMPORTANT: This application does NOT check if the generated path exists on the filesystem.
 * It only resolves the string pattern. Plugins are responsible for creating the required 
 * directories and checking for file existence/overwrites as needed.
 */
object PathPatternResolver {

    private val MODIFIER_REGEX = Regex("""\{([^}]+)\}""")

    /**
     * Checks if a pattern can be fully resolved given the set of available parameter IDs.
     */
    fun canResolve(pattern: String, availableInputs: Set<String>): Boolean {
        val matches = MODIFIER_REGEX.findAll(pattern)
        for (match in matches) {
            val token = match.groupValues[1]
            val paramId = token.substringBefore(".")
            if (!availableInputs.contains(paramId)) {
                return false
            }
        }
        return true
    }

    /**
     * Resolves the given pattern using the provided values map.
     * Throws an exception if a required variable is missing or if the resulting path is invalid
     * (e.g., escaping root via too many `..`).
     * 
     * @return The evaluated path string.
     */
    fun resolve(pattern: String, values: Map<String, String>): String {
        var resolvedPattern = pattern
        val matches = MODIFIER_REGEX.findAll(pattern).toList().reversed()

        for (match in matches) {
            val fullToken = match.groupValues[0] // e.g., "{input_file.nameWithoutExtension}"
            val innerToken = match.groupValues[1] // e.g., "input_file.nameWithoutExtension"

            val paramId = innerToken.substringBefore(".")
            val modifier = if (innerToken.contains(".")) innerToken.substringAfter(".") else null

            val rawValue = values[paramId]
                ?: throw IllegalArgumentException("Missing required parameter for path generation: $paramId")

            val substitutedValue = applyModifier(rawValue, modifier)

            resolvedPattern = resolvedPattern.replaceRange(match.range, substitutedValue)
        }

        // Validate the path to ensure it doesn't do invalid traversal (e.g. too many ..)
        val normalized = normalizeAndValidatePath(resolvedPattern)
        return normalized
    }

    /**
     * Attempts to resolve the pattern but returns null if variables are missing,
     * instead of throwing an exception. Still throws if the resulting path is invalid.
     */
    fun tryResolve(pattern: String, values: Map<String, String>): String? {
        return try {
            resolve(pattern, values)
        } catch (e: IllegalArgumentException) {
            if (e.message?.startsWith("Missing required parameter") == true) {
                null
            } else {
                throw e
            }
        }
    }

    private fun applyModifier(pathString: String, modifier: String?): String {
        // If it's empty, we can't extract modifiers like name or ext effectively
        if (pathString.isBlank()) return ""

        val path = Path(pathString)
        val isWindows = pathString.contains(":\\") || pathString.contains(":/")

        return when (modifier) {
            "dir" -> {
                val parent = path.parent?.toString() ?: ""
                // Edge case handling for windows roots
                if (isWindows && parent.isEmpty()) {
                    pathString.substringBefore("\\").substringBefore("/") + "\\"
                } else {
                    parent
                }
            }

            "name" -> path.name
            "nameWithoutExtension" -> {
                val name = path.name
                if (name.contains(".")) name.substringBeforeLast(".") else name
            }

            "ext" -> {
                val name = path.name
                if (name.contains(".")) name.substringAfterLast(".") else ""
            }

            null, "" -> pathString
            else -> throw IllegalArgumentException("Unknown path modifier: $modifier")
        }
    }

    private fun normalizeAndValidatePath(pathStr: String): String {
        val separator = if (pathStr.contains("\\")) "\\" else "/"
        val parts = pathStr.split(Regex("[\\\\/]"))

        val resolvedParts = mutableListOf<String>()
        var isAbsoluteUnix = pathStr.startsWith("/")
        var windowsRoot = ""

        if (parts.isNotEmpty() && parts[0].endsWith(":")) {
            windowsRoot = parts[0]
        }

        for (i in parts.indices) {
            val part = parts[i]
            if (part == "." || part.isEmpty()) {
                // Keep empty parts only if it's the root (e.g. first part of /a or first part after C:)
                if (i == 0 && isAbsoluteUnix) {
                    resolvedParts.add("")
                }
                continue
            } else if (part == "..") {
                if (resolvedParts.isEmpty() || (resolvedParts.size == 1 && resolvedParts[0] == "") || (resolvedParts.size == 0 && windowsRoot.isNotEmpty())) {
                    throw IllegalArgumentException("Invalid path generated: escapes root directory ($pathStr)")
                }
                resolvedParts.removeLast()
            } else {
                resolvedParts.add(part)
            }
        }

        if (resolvedParts.isEmpty()) {
            return if (windowsRoot.isNotEmpty()) "$windowsRoot$separator" else if (isAbsoluteUnix) "/" else "."
        }

        var normalized = resolvedParts.joinToString(separator)
        if (windowsRoot.isNotEmpty() && !normalized.startsWith(windowsRoot)) {
            normalized = "$windowsRoot$separator$normalized"
        } else if (isAbsoluteUnix && !normalized.startsWith("/")) {
            normalized = "/$normalized"
        }

        return normalized
    }
}
