package org.wip.plugintoolkit.features.plugin.utils

import org.wip.plugintoolkit.features.plugin.utils.SettingsUtils.calculateAutogeneratedPath
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

class SettingsUtilsTest {

    @Test
    fun testRoleDeserialization() {
        val jsonString = """
            {
                "description": "The input file",
                "type": {
                    "type": "primitive",
                    "primitiveType": "STRING"
                },
                "required": true,
                "role": "INPUT_LOCATION"
            }
        """.trimIndent()
        
        val jsonConfig = kotlinx.serialization.json.Json {
            ignoreUnknownKeys = true
            isLenient = true
        }
        
        val result = jsonConfig.decodeFromString<org.wip.plugintoolkit.api.ParameterMetadata>(jsonString)
        println("PARSED ROLE: " + result.role)
        assertEquals(org.wip.plugintoolkit.api.ParameterRole.INPUT_LOCATION, result.role)
    }

    @Test
    fun testCalculateAutogeneratedPath() {
        // Test basic replacement
        assertEquals(
            "input/folder/converted.txt",
            calculateAutogeneratedPath("{in}/converted.txt", mapOf("in" to "input/folder"))
        )
        
        // Test normalization with ..
        assertEquals(
            "input/converted.txt",
            calculateAutogeneratedPath("{in}/../converted.txt", mapOf("in" to "input/folder"))
        )

        // Test normalization with multiple ..
        assertEquals(
            "converted.txt",
            calculateAutogeneratedPath("{in}/../../converted.txt", mapOf("in" to "input/folder"))
        )
        
        // Test multiple parameters
        assertEquals(
            "input/folder/output.txt",
            calculateAutogeneratedPath("{folder}/{file}.txt", mapOf("folder" to "input", "file" to "folder/output"))
        )
        
        // Test missing parameter
        assertNull(
            calculateAutogeneratedPath("{in}/converted.txt", emptyMap())
        )
        
        // Test Windows paths
        assertEquals(
            "C:\\folder\\converted.txt",
            calculateAutogeneratedPath("{in}\\..\\converted.txt", mapOf("in" to "C:\\folder\\subfolder"))
        )
    }
}
