package org.wip.plugintoolkit.features.flows

import org.wip.plugintoolkit.features.flows.model.Offset
import org.wip.plugintoolkit.api.Capability
import org.wip.plugintoolkit.api.PluginInfo
import org.wip.plugintoolkit.features.flows.model.Flow
import org.wip.plugintoolkit.features.flows.model.Node
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class FlowBrokenTest {

    private val dummyPluginInfo = PluginInfo(
        id = "test.plugin",
        name = "Test Plugin",
        version = "1.0",
        description = "Test plugin"
    )

    private val capabilityA = Capability(
        name = "Capability A",
        description = "Does A",
        returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT)
    )

    private val capabilityB = Capability(
        name = "Capability B",
        description = "Does B",
        returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT)
    )

    private fun createCapabilityNode(capability: Capability, isBroken: Boolean = false): Node.CapabilityNode {
        return Node.CapabilityNode(
            id = capability.name.hashCode().toLong(),
            position = Offset.Zero,
            pluginInfo = dummyPluginInfo,
            capability = capability,
            inputs = emptyList(),
            outputs = emptyList(),
            isBroken = isBroken
        )
    }

    @Test
    fun `test flow is not broken when all capabilities are active and no nodes are explicitly broken`() {
        val flow = Flow(
            name = "Test Flow",
            nodes = listOf(
                createCapabilityNode(capabilityA),
                createCapabilityNode(capabilityB)
            )
        )

        val activeCapabilities = setOf("Capability A", "Capability B")
        assertFalse(flow.isBroken(activeCapabilities), "Flow should not be broken")
    }

    @Test
    fun `test flow is broken when a capability is missing from active capabilities`() {
        val flow = Flow(
            name = "Test Flow",
            nodes = listOf(
                createCapabilityNode(capabilityA),
                createCapabilityNode(capabilityB)
            )
        )

        // Only Capability A is active, meaning Capability B is missing
        val activeCapabilities = setOf("Capability A")
        assertTrue(flow.isBroken(activeCapabilities), "Flow should be broken due to missing capability B")
    }

    @Test
    fun `test flow is broken when a node is explicitly marked as broken even if its capability is active`() {
        val flow = Flow(
            name = "Test Flow",
            nodes = listOf(
                createCapabilityNode(capabilityA, isBroken = true)
            )
        )

        val activeCapabilities = setOf("Capability A")
        assertTrue(
            flow.isBroken(activeCapabilities),
            "Flow should be broken because the node is explicitly marked as broken"
        )
    }

    @Test
    fun `test flow is not broken when empty`() {
        val flow = Flow(
            name = "Empty Flow",
            nodes = emptyList()
        )

        val activeCapabilities = setOf("Capability A")
        assertFalse(flow.isBroken(activeCapabilities), "Empty flow should not be broken")
    }

    @Test
    fun `test flow is broken when capability node is missing a required input parameter`() {
        val capWithRequiredParam = Capability(
            name = "Capability With Required Param",
            description = "Requires param",
            returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT),
            parameters = mapOf(
                "reqInput" to org.wip.plugintoolkit.api.ParameterMetadata(
                    description = "Required input",
                    type = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.STRING),
                    required = true,
                    defaultValue = null,
                    autogeneratedPattern = null
                )
            )
        )
        val node = createCapabilityNode(capWithRequiredParam)
        val flow = Flow(
            name = "Broken Param Flow",
            nodes = listOf(node)
        )

        val active = setOf("Capability With Required Param")
        assertTrue(flow.isBroken(active), "Flow should be broken when node is missing required parameter port")
    }

    @Test
    fun `test flow is not broken when required parameter has default value`() {
        val capWithDefaultParam = Capability(
            name = "Capability With Default Param",
            description = "Has default param",
            returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT),
            parameters = mapOf(
                "defaultInput" to org.wip.plugintoolkit.api.ParameterMetadata(
                    description = "Input with default",
                    type = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.STRING),
                    required = true,
                    defaultValue = kotlinx.serialization.json.JsonPrimitive("standard_default")
                )
            )
        )
        val node = createCapabilityNode(capWithDefaultParam)
        val flow = Flow(
            name = "Valid Default Flow",
            nodes = listOf(node)
        )

        val active = setOf("Capability With Default Param")
        assertFalse(flow.isBroken(active), "Flow should not be broken when required parameter has default value")
    }

    @Test
    fun `test reconcileCapabilityNodePorts marks node broken if required parameter without default is missing`() {
        val oldCap = Capability(
            name = "Capability Alpha",
            description = "Old version",
            returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT)
        )
        val node = createCapabilityNode(oldCap)

        val newCap = Capability(
            name = "Capability Alpha",
            description = "New version with required param",
            returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT),
            parameters = mapOf(
                "apiKey" to org.wip.plugintoolkit.api.ParameterMetadata(
                    description = "Secret key",
                    type = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.STRING),
                    required = true,
                    defaultValue = null
                )
            )
        )

        val reconciled = org.wip.plugintoolkit.features.flows.model.MigrationEngine.reconcileCapabilityNodePorts(
            node = node,
            actualCapability = newCap,
            currentPluginInfo = dummyPluginInfo
        )

        assertTrue(reconciled.isBroken, "Reconciled node should be broken because required param has no default")
        assertTrue(reconciled.inputs.any { it.id == "apiKey" }, "Reconciled node should have added the new port")
    }

    @Test
    fun `test reconcileCapabilityNodePorts keeps node unbroken if required parameter has default`() {
        val oldCap = Capability(
            name = "Capability Beta",
            description = "Old version",
            returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT)
        )
        val node = createCapabilityNode(oldCap)

        val newCap = Capability(
            name = "Capability Beta",
            description = "New version with default param",
            returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT),
            parameters = mapOf(
                "port" to org.wip.plugintoolkit.api.ParameterMetadata(
                    description = "Port number",
                    type = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.INT),
                    required = true,
                    defaultValue = kotlinx.serialization.json.JsonPrimitive(8080)
                )
            )
        )

        val reconciled = org.wip.plugintoolkit.features.flows.model.MigrationEngine.reconcileCapabilityNodePorts(
            node = node,
            actualCapability = newCap,
            currentPluginInfo = dummyPluginInfo
        )

        assertFalse(reconciled.isBroken, "Reconciled node should not be broken when required param has default")
        val addedPort = reconciled.inputs.find { it.id == "port" }
        kotlin.test.assertNotNull(addedPort, "Added port should exist")
        kotlin.test.assertEquals(kotlinx.serialization.json.JsonPrimitive(8080), addedPort.defaultValue)
    }

    @Test
    fun `test broken node heals to isBroken false when refreshed against valid manifest`() {
        val brokenNode = createCapabilityNode(capabilityA, isBroken = true)
        assertTrue(brokenNode.isBroken, "Node starts broken")

        val manifest = org.wip.plugintoolkit.api.PluginManifest(
            manifestVersion = "1.0",
            plugin = dummyPluginInfo,
            requirements = org.wip.plugintoolkit.api.Requirements(minMemoryMb = 256, minExecutionTimeMs = 1000),
            capabilities = listOf(capabilityA)
        )

        val healed = org.wip.plugintoolkit.features.flows.model.MigrationEngine.refreshCapabilityNode(
            node = brokenNode,
            manifest = manifest
        )

        assertFalse(healed.isBroken, "Healed node must have isBroken = false")
        kotlin.test.assertEquals(brokenNode.id, healed.id)
    }

    @Test
    fun `test targeted migration does not mark nodes from other plugins as broken`() = kotlinx.coroutines.test.runTest {
        val otherPluginInfo = PluginInfo(
            id = "other.plugin",
            name = "Other Plugin",
            version = "1.0",
            description = "Other"
        )
        val otherNode = Node.CapabilityNode(
            id = 999L,
            position = Offset.Zero,
            pluginInfo = otherPluginInfo,
            capability = Capability(
                name = "Other Cap",
                description = "Other",
                returnType = org.wip.plugintoolkit.api.DataType.Primitive(org.wip.plugintoolkit.api.PrimitiveType.UNIT)
            ),
            inputs = emptyList(),
            outputs = emptyList(),
            isBroken = false
        )

        val targetNode = createCapabilityNode(capabilityA, isBroken = false)

        val flow = Flow(
            name = "Mixed Plugins Flow",
            nodes = listOf(targetNode, otherNode)
        )

        // Simulate targeted update for dummyPluginInfo where otherPlugin is NOT in currentManifests
        val currentManifests = mapOf(
            dummyPluginInfo.id to org.wip.plugintoolkit.api.PluginManifest(
                manifestVersion = "1.0",
                plugin = dummyPluginInfo,
                requirements = org.wip.plugintoolkit.api.Requirements(minMemoryMb = 256, minExecutionTimeMs = 1000),
                capabilities = listOf(capabilityA)
            )
        )

        val result = org.wip.plugintoolkit.features.flows.model.MigrationEngine.migrateFlow(
            flow = flow,
            currentManifests = currentManifests,
            getMigrations = { emptyList() },
            targetPluginId = dummyPluginInfo.id
        )

        val migratedOtherNode = result.migratedFlow.nodes.find { it.id == 999L } as? Node.CapabilityNode
        kotlin.test.assertNotNull(migratedOtherNode)
        assertFalse(migratedOtherNode.isBroken, "Other plugin's node MUST NOT be marked broken during targeted update")
    }
}

