package org.wip.plugintoolkit.features.plugin.ui

import androidx.compose.ui.test.ExperimentalTestApi
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.runDesktopComposeUiTest
import org.wip.plugintoolkit.api.Capability
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.PrimitiveType
import kotlin.test.Test

@OptIn(ExperimentalTestApi::class)
class CapabilityTesterTest {

    @Test
    fun testCapabilityTester_executeButtonDisabledWhenLockFalse() = runDesktopComposeUiTest {
        val capability = Capability(
            name = "testCap",
            description = "Test Capability",
            returnType = DataType.Primitive(PrimitiveType.UNIT),
            requiredLocks = listOf("feature_unlocked")
        )

        setContent {
            CapabilityTester(
                capability = capability,
                parameterValues = emptyMap(),
                onParameterChange = { _, _ -> },
                isParameterAutoGenerated = { false },
                saveResults = false,
                onSaveResultsChange = {},
                activeJobs = emptyList(),
                providedLocks = mapOf("feature_unlocked" to false),
                onExecute = {}
            )
        }

        onNodeWithText("Requires lock: feature_unlocked").assertExists()
    }
}
