package org.wip.plugintoolkit.features.plugin.ui

import androidx.compose.ui.test.ExperimentalTestApi
import androidx.compose.ui.test.onNodeWithContentDescription
import androidx.compose.ui.test.runDesktopComposeUiTest
import org.wip.plugintoolkit.api.Capability
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.PrimitiveType
import kotlin.test.Test

@OptIn(ExperimentalTestApi::class)
class LockedCapabilityGUITest {

    @Test
    fun testLockedCapability_displaysLockIcon() = runDesktopComposeUiTest {
        val lockedCapability = Capability(
            name = "LockedCapabilityTest",
            description = "A capability requiring a lock",
            returnType = DataType.Primitive(PrimitiveType.UNIT),
            requiredLocks = listOf("feature_unlocked")
        )

        setContent {
            CapabilityTester(
                capability = lockedCapability,
                parameterValues = emptyMap(),
                onParameterChange = { _, _ -> },
                isParameterAutoGenerated = { false },
                saveResults = false,
                onSaveResultsChange = {},
                activeJobs = emptyList(),
                providedLocks = mapOf("feature_unlocked" to false),
                onExecute = {}
            )
        }

        // Must display standard lock icon with contentDescription "Locked capability icon"
        onNodeWithContentDescription("Locked capability icon").assertExists()
    }
}
