package org.wip.plugintoolkit.features.plugin.logic

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonPrimitive
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.PrimitiveType
import org.wip.plugintoolkit.api.SettingMetadata
import org.wip.plugintoolkit.features.flows.logic.PathPatternResolver
import org.wip.plugintoolkit.features.plugin.model.PluginSettingsStore
import org.wip.plugintoolkit.features.plugin.utils.SettingsUtils

internal fun resolveAutogeneratedSettings(
    metadata: Map<String, SettingMetadata>,
    settings: Map<String, JsonElement>,
    additionalValues: Map<String, JsonElement> = emptyMap()
): Map<String, JsonElement> {
    val resolvedSettings = settings.toMutableMap()
    val defaults = metadata.mapNotNull { (key, value) -> value.defaultValue?.let { key to it } }.toMap()

    repeat(metadata.size.coerceAtLeast(1)) {
        var changed = false
        metadata.forEach { (key, settingMetadata) ->
            val pattern = settingMetadata.autogeneratedPattern?.takeIf { it.isNotBlank() } ?: return@forEach
            val availableValues = defaults + additionalValues + resolvedSettings
            val stringValues = availableValues.mapValues { (valueKey, value) ->
                val valueType = metadata[valueKey]?.type
                if (valueType != null) SettingsUtils.jsonToString(value, valueType) else value.toString().trim('"')
            }
            val generated = runCatching { PathPatternResolver.tryResolve(pattern, stringValues) }.getOrNull()
                ?: return@forEach
            val generatedValue = generatedSettingValue(generated, settingMetadata.type) ?: return@forEach
            if (resolvedSettings[key] != generatedValue) {
                resolvedSettings[key] = generatedValue
                changed = true
            }
        }
        if (!changed) return resolvedSettings
    }

    return resolvedSettings
}

internal fun PluginSettingsStore.withResolvedAutogeneratedSettings(
    metadata: Map<String, SettingMetadata>
): PluginSettingsStore {
    val resolved = resolveAutogeneratedSettings(metadata, settings, globalParams)
    return if (resolved == settings) this else copy(settings = resolved)
}

private fun generatedSettingValue(value: String, type: DataType): JsonElement? = when (type) {
    is DataType.Primitive -> when (type.primitiveType) {
        PrimitiveType.STRING, PrimitiveType.ANY, PrimitiveType.UNKNOWN -> JsonPrimitive(value)
        PrimitiveType.BOOLEAN -> value.toBooleanStrictOrNull()?.let(::JsonPrimitive)
        PrimitiveType.INT -> value.toIntOrNull()?.let(::JsonPrimitive)
        PrimitiveType.LONG -> value.toLongOrNull()?.let(::JsonPrimitive)
        PrimitiveType.SHORT -> value.toShortOrNull()?.let { JsonPrimitive(it.toInt()) }
        PrimitiveType.BYTE -> value.toByteOrNull()?.let { JsonPrimitive(it.toInt()) }
        PrimitiveType.DOUBLE -> value.toDoubleOrNull()?.let(::JsonPrimitive)
        PrimitiveType.FLOAT -> value.toFloatOrNull()?.let { JsonPrimitive(it.toDouble()) }
        PrimitiveType.UNIT -> null
    }
    else -> value.takeIf { it.isNotBlank() }?.let { runCatching { SettingsUtils.stringToJson(it, type) }.getOrNull() }
}
