package org.wip.plugintoolkit.api

import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class SettingMetadataBinaryCompatibilityTest {
    @Test
    fun `retains pre-hints JVM constructor`() {
        val oldParameterTypes = listOf(
            JsonElement::class.java,
            String::class.java,
            DataType::class.java,
            Boolean::class.javaPrimitiveType,
            Boolean::class.javaPrimitiveType,
            ParameterConstraints::class.java,
            List::class.java
        )

        assertTrue(
            SettingMetadata::class.java.declaredConstructors.any { constructor ->
                constructor.parameterTypes.toList() == oldParameterTypes
            },
            "SettingMetadata must keep the constructor used by plugins compiled against the previous API"
        )
    }

    @Test
    fun `retains pre-hints copy bridges`() {
        val methods = SettingMetadata::class.java.declaredMethods
        val oldCopy = methods.single { it.name == "copy" && it.parameterCount == 7 }
        val oldDefaultCopy = methods.single { it.name == "copy\$default" && it.parameterCount == 10 }
        val original = SettingMetadata(
            defaultValue = JsonPrimitive("value"),
            description = "description",
            type = DataType.Primitive(PrimitiveType.STRING),
            semanticTypes = listOf(SemanticType(null, "text", null)),
            autogeneratedPattern = "{input}"
        )

        val copied = oldDefaultCopy.invoke(
            null, original, null, null, null, false, false, null, null, 0x7F, null
        ) as SettingMetadata

        assertEquals(original, copied)
        assertEquals(SettingMetadata::class.java, oldCopy.returnType)
    }
}
