package org.wip.plugintoolkit.features.flows

import androidx.compose.ui.geometry.Offset
import io.mockk.coEvery
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkObject
import io.mockk.unmockkAll
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.json.JsonPrimitive
import org.koin.core.context.stopKoin
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.ParameterRole
import org.wip.plugintoolkit.api.PluginInfo
import org.wip.plugintoolkit.api.PluginManifest
import org.wip.plugintoolkit.api.PluginRequest
import org.wip.plugintoolkit.api.PrimitiveType
import org.wip.plugintoolkit.api.Requirements
import org.wip.plugintoolkit.features.flows.model.Connection
import org.wip.plugintoolkit.features.flows.model.Flow
import org.wip.plugintoolkit.features.flows.model.InputPort
import org.wip.plugintoolkit.features.flows.model.Node
import org.wip.plugintoolkit.features.job.logic.JobManager
import org.wip.plugintoolkit.features.job.logic.JobWorker
import org.wip.plugintoolkit.features.job.model.BackgroundJob
import org.wip.plugintoolkit.features.job.model.JobType
import org.wip.plugintoolkit.features.plugin.logic.PluginLoader
import org.wip.plugintoolkit.features.plugin.logic.PluginManager
import org.wip.plugintoolkit.features.settings.logic.SettingsRepository
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertTrue

class JobWorkerFlowSandboxTest : JobWorkerFlowTestBase() {

    @BeforeTest
    fun setup() {
        mockkObject(PluginLoader)
    }

    @AfterTest
    fun tearDown() {
        stopKoin()
        unmockkAll()
    }

    @Test
    fun testAutogeneratedPatternIsSandboxed() = runTest {
        val pluginManager = mockk<PluginManager>(relaxed = true)
        val mockPluginEntry = mockk<org.wip.plugintoolkit.api.PluginEntry>(relaxed = true)
        val mockProcessor = mockk<org.wip.plugintoolkit.api.DataProcessor>(relaxed = true)

        every { PluginLoader.getPluginById("test-plugin") } returns mockPluginEntry
        every { mockPluginEntry.getProcessor() } answers { Result.success(mockProcessor) }
        every { mockPluginEntry.getManifest() } answers {
            Result.success(
                PluginManifest(
                    manifestVersion = "1.0",
                    plugin = PluginInfo(id = "test-plugin", name = "Test", version = "1.0", description = "Test"),
                    requirements = Requirements(minMemoryMb = 128, minExecutionTimeMs = 100),
                    capabilities = listOf(
                        org.wip.plugintoolkit.api.Capability(
                            name = "test_capability",
                            description = "test cap",
                            returnType = DataType.Primitive(PrimitiveType.STRING),
                            parameters = mapOf(
                                "input_file" to ParameterMetadata(
                                    description = "Input",
                                    type = DataType.Primitive(PrimitiveType.STRING),
                                    role = ParameterRole.INPUT_LOCATION
                                ),
                                "output_file" to ParameterMetadata(
                                    description = "Output",
                                    type = DataType.Primitive(PrimitiveType.STRING),
                                    role = ParameterRole.OUTPUT_LOCATION,
                                    autogeneratedPattern = "{input_file.dir}/../escape.txt" // Traversal Pattern
                                )
                            )
                        )
                    )
                )
            )
        }

        var capturedParameters: Map<String, kotlinx.serialization.json.JsonElement>? = null
        coEvery { mockProcessor.process(any(), any()) } coAnswers {
            val req = firstArg<PluginRequest>()
            capturedParameters = req.parameters
            org.wip.plugintoolkit.api.ExecutionResult.Success(
                org.wip.plugintoolkit.api.PluginResponse(
                    result = kotlinx.serialization.json.JsonObject(mapOf("result" to JsonPrimitive("done")))
                )
            )
        }

        val inputNode = createInputNode(1, "source", DataType.Primitive(PrimitiveType.STRING))
        val capabilityNode = Node.CapabilityNode(
            id = 2,
            position = Offset.Zero,
            capability = mockPluginEntry.getManifest().getOrThrow().capabilities.first(),
            pluginInfo = PluginInfo(id = "test-plugin", name = "Test Plugin", version = "1.0", description = "Test"),
            inputs = listOf(
                InputPort(id = "input_file", name = "input", dataType = DataType.Primitive(PrimitiveType.STRING))
            ),
            outputs = emptyList()
        )

        val flow = Flow(
            name = "test_flow",
            nodes = listOf(inputNode, capabilityNode),
            connections = listOf(Connection(1, "output_data", 2, "input_file"))
        )

        val job = BackgroundJob(
            id = "test-job-sandbox-traversal",
            name = "Sandbox Job Traversal",
            type = JobType.Flow,
            pluginId = "system",
            capabilityName = "test_flow",
            parameters = mapOf("1" to JsonPrimitive("C:/some/external/folder/test_image.png"))
        )

        val persistence = FakeSettingsPersistence()
        val settingsRepo = SettingsRepository(persistence, backgroundScope)
        val jobManager = JobManager(backgroundScope, settingsRepo)
        
        val engine = org.wip.plugintoolkit.features.job.logic.FlowEngine(
            jobManager,
            org.wip.plugintoolkit.features.job.logic.DefaultSystemNodeExecutorRegistry(mockk(relaxed = true)),
            pluginManager,
            mockk(relaxed = true),
            backgroundScope
        )

        engine.executeSubFlowRecursively(flow, job, "/tmp")

        val generatedOutputPath = (capturedParameters?.get("output_file") as? JsonPrimitive)?.content
        checkNotNull(generatedOutputPath) { "output_file parameter was not generated" }

        assertTrue(
            generatedOutputPath.contains("node_2"),
            "Output path does not contain node sandbox directory: $generatedOutputPath"
        )
        assertTrue(
            generatedOutputPath.contains("escape.txt"),
            "Output path does not preserve the generated file name: $generatedOutputPath"
        )
        assertTrue(
            !generatedOutputPath.contains("some/external/folder") && !generatedOutputPath.contains(".."),
            "Output path contains traversal strings or original external directory, escaping the sandbox! $generatedOutputPath"
        )
    }
}
