package org.wip.plugintoolkit.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.put


/**
 * Represents the type of data exchanged between the host and the plugin.
 */
@Serializable
sealed class DataType {
    /**
     * Checks if a value is "provided" for this data type.
     * This is used to validate required settings or parameters.
     * For example, a String is provided if it's not blank.
     * An Array is provided if it's not empty.
     */
    abstract fun isProvided(value: JsonElement?): Boolean

    /**
     * A basic primitive type (String, Int, Boolean, etc.).
     */
    @Serializable
    @SerialName("primitive")
    data class Primitive(val primitiveType: PrimitiveType) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            if (value == null || value is JsonNull) return false
            return when (primitiveType) {
                PrimitiveType.STRING -> (value as? JsonPrimitive)?.content?.isNotBlank() ?: false
                else -> true // Other primitives are provided if they exist
            }
        }
    }

    /**
     * A collection of items of the same type.
     */
    @Serializable
    @SerialName("array")
    data class Array(val items: DataType) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            if (value == null || value is JsonNull) return false
            return (value as? JsonArray)?.isNotEmpty() ?: true
        }
    }

    /**
     * A custom object type represented by its class name.
     */
    @Serializable
    @SerialName("object")
    data class Object(
        val className: String, 
        val namespace: String? = null,
        val properties: Map<String, DataType> = emptyMap()
    ) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            return value != null && value !is JsonNull
        }
    }

    /**
     * An enumeration type with a set of predefined options.
     */
    @Serializable
    @SerialName("enum")
    data class Enum(
        val className: String, 
        val options: List<String>, 
        val namespace: String? = null,
        val optionRequirements: Map<String, List<String>> = emptyMap()
    ) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            return value != null && value !is JsonNull
        }
    }

    /**
     * A map of strings to a specific value type.
     */
    @Serializable
    @SerialName("map")
    data class MapType(val valueType: DataType) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            if (value == null || value is JsonNull) return false
            return (value as? JsonObject)?.isNotEmpty() ?: true
        }
    }
}

@Serializable
enum class PrimitiveType {
    DOUBLE, INT, STRING, BOOLEAN, UNIT, ANY
}


@Serializable
data class ParameterConstraints(
    val minValue: Double? = null,
    val maxValue: Double? = null,
    val minLength: Int? = null,
    val maxLength: Int? = null,
    val regex: String? = null,
    val multiSelect: Boolean? = null,
    val minChoices: Int? = null,
    val maxChoices: Int? = null
)

@Serializable
data class SettingMetadata(
    val defaultValue: JsonElement? = null,
    val description: String,
    val type: DataType,
    val required: Boolean = false,
    val secret: Boolean = false
)

/**
 * The complete manifest of a plugin, describing its capabilities and requirements.
 *
 * This object is typically generated by KSP and bundled with the plugin.
 */
@Serializable
data class PluginManifest(
    val manifestVersion: String,
    val plugin: PluginInfo,
    val requirements: Requirements,
    val defaultParameters: Map<String, ParameterMetadata>? = null,
    val capabilities: List<Capability> = emptyList(),
    val actions: List<PluginAction> = emptyList(),
    val settings: Map<String, SettingMetadata>? = null,
    val changelog: Changelog? = null,
    val hasUpdateHandler: Boolean = false,
    val hasSetupHandler: Boolean = false,
    val hasMigrations: Boolean = false
)

@Serializable
data class PluginMigration(
    val fromVersion: String,
    val toVersion: String,
    val capabilityMigrations: List<CapabilityMigration> = emptyList(),
    val settingMigrations: List<SettingMigration> = emptyList(),
    val objectMigrations: List<ObjectMigration> = emptyList()
)

@Serializable
data class CapabilityMigration(
    val oldName: String,
    val newName: String?, // null means capability is removed/unsupported
    val isDropInReplacement: Boolean = false,
    val portMigrations: List<PortMigration> = emptyList()
)

@Serializable
data class PortMigration(
    val oldName: String,
    val newName: String? // null means port is removed
)

@Serializable
data class SettingMigration(
    val oldName: String,
    val newName: String? // null means setting is removed
)

@Serializable
data class ObjectMigration(
    val oldClassName: String,
    val newClassName: String?, // null means custom object is removed
    val propertyMigrations: List<PropertyMigration> = emptyList()
)

@Serializable
data class PropertyMigration(
    val oldName: String,
    val newName: String?
)

@Serializable
data class Changelog(
    val releases: List<Release>
)

@Serializable
data class Release(
    val version: String,
    val date: String,
    val categories: Map<String, List<String>>
)

@Serializable
enum class OS {
    LINUX, WINDOWS, MACOS
}

@Serializable
data class PluginInfo(
    val id: String,
    val name: String,
    val version: String,
    val description: String,
    val supportedOs: List<OS> = emptyList()
)

@Serializable
data class Requirements(
    val minMemoryMb: Int,
    val minExecutionTimeMs: Int,
    val targetAppVersion: String? = ApiConfig.VERSION
)

@Serializable(with = ParameterMetadataSerializer::class)
data class ParameterMetadata(
    val defaultValue: JsonElement? = null,
    val description: String,
    val type: DataType,
    val constraints: ParameterConstraints? = null,
    val required: Boolean = false,
    val secret: Boolean = false,
    val semanticTypes: List<SemanticType> = emptyList()
)

object ParameterMetadataSerializer : KSerializer<ParameterMetadata> {
    override val descriptor: SerialDescriptor = ParameterMetadataSurrogate.serializer().descriptor

    override fun serialize(encoder: Encoder, value: ParameterMetadata) {
        val surrogate = ParameterMetadataSurrogate(
            defaultValue = value.defaultValue,
            description = value.description,
            type = value.type,
            constraints = value.constraints,
            required = value.required,
            secret = value.secret,
            semanticTypes = value.semanticTypes
        )
        encoder.encodeSerializableValue(ParameterMetadataSurrogate.serializer(), surrogate)
    }

    override fun deserialize(decoder: Decoder): ParameterMetadata {
        val input = decoder as? JsonDecoder ?: throw SerializationException("This serializer only supports JSON")
        val element = input.decodeJsonElement() as JsonObject
        val hasSemanticTypes = "semanticTypes" in element
        val finalElement = if (!hasSemanticTypes) {
            val legacySemanticType = element["semanticType"]?.jsonPrimitive?.contentOrNull
            val parsedList = parseSemanticTypes(legacySemanticType).map { type ->
                buildJsonObject {
                    put("namespace", type.namespace)
                    put("name", type.name)
                    put("variant", type.variant)
                }
            }
            JsonObject(element.filterKeys { it != "semanticType" } + ("semanticTypes" to JsonArray(parsedList)))
        } else {
            JsonObject(element.filterKeys { it != "semanticType" })
        }
        val surrogate = input.json.decodeFromJsonElement(ParameterMetadataSurrogate.serializer(), finalElement)
        return ParameterMetadata(
            defaultValue = surrogate.defaultValue,
            description = surrogate.description,
            type = surrogate.type,
            constraints = surrogate.constraints,
            required = surrogate.required,
            secret = surrogate.secret,
            semanticTypes = surrogate.semanticTypes
        )
    }
}

@Serializable
@SerialName("ParameterMetadata")
private class ParameterMetadataSurrogate(
    val defaultValue: JsonElement? = null,
    val description: String,
    val type: DataType,
    val constraints: ParameterConstraints? = null,
    val required: Boolean = false,
    val secret: Boolean = false,
    val semanticTypes: List<SemanticType> = emptyList()
)

@Serializable(with = OutputMetadataSerializer::class)
data class OutputMetadata(
    val name: String,
    val description: String,
    val type: DataType,
    val semanticTypes: List<SemanticType> = emptyList()
)

object OutputMetadataSerializer : KSerializer<OutputMetadata> {
    override val descriptor: SerialDescriptor = OutputMetadataSurrogate.serializer().descriptor

    override fun serialize(encoder: Encoder, value: OutputMetadata) {
        val surrogate = OutputMetadataSurrogate(
            name = value.name,
            description = value.description,
            type = value.type,
            semanticTypes = value.semanticTypes
        )
        encoder.encodeSerializableValue(OutputMetadataSurrogate.serializer(), surrogate)
    }

    override fun deserialize(decoder: Decoder): OutputMetadata {
        val input = decoder as? JsonDecoder ?: throw SerializationException("This serializer only supports JSON")
        val element = input.decodeJsonElement() as JsonObject
        val hasSemanticTypes = "semanticTypes" in element
        val finalElement = if (!hasSemanticTypes) {
            val legacySemanticType = element["semanticType"]?.jsonPrimitive?.contentOrNull
            val parsedList = parseSemanticTypes(legacySemanticType).map { type ->
                buildJsonObject {
                    put("namespace", type.namespace)
                    put("name", type.name)
                    put("variant", type.variant)
                }
            }
            JsonObject(element.filterKeys { it != "semanticType" } + ("semanticTypes" to JsonArray(parsedList)))
        } else {
            JsonObject(element.filterKeys { it != "semanticType" })
        }
        val surrogate = input.json.decodeFromJsonElement(OutputMetadataSurrogate.serializer(), finalElement)
        return OutputMetadata(
            name = surrogate.name,
            description = surrogate.description,
            type = surrogate.type,
            semanticTypes = surrogate.semanticTypes
        )
    }
}

@Serializable
@SerialName("OutputMetadata")
private class OutputMetadataSurrogate(
    val name: String,
    val description: String,
    val type: DataType,
    val semanticTypes: List<SemanticType> = emptyList()
)

@Serializable
enum class CapabilityContext {
    ANY, FLOW_ONLY, STANDALONE_ONLY
}

/**
 * Metadata for a specific capability provided by the plugin.
 */
@Serializable(with = CapabilitySerializer::class)
data class Capability(
    val name: String,
    val description: String,
    val parameters: Map<String, ParameterMetadata>? = null,
    val returnType: DataType,
    val semanticTypes: List<SemanticType> = emptyList(),
    val outputs: List<OutputMetadata>? = null,
    val isPausable: Boolean = false,
    val isCancellable: Boolean = true,
    val context: CapabilityContext = CapabilityContext.ANY,
    val requiresSettings: List<String> = emptyList()
)

object CapabilitySerializer : KSerializer<Capability> {
    override val descriptor: SerialDescriptor = CapabilitySurrogate.serializer().descriptor

    override fun serialize(encoder: Encoder, value: Capability) {
        val surrogate = CapabilitySurrogate(
            name = value.name,
            description = value.description,
            parameters = value.parameters,
            returnType = value.returnType,
            semanticTypes = value.semanticTypes,
            outputs = value.outputs,
            isPausable = value.isPausable,
            isCancellable = value.isCancellable,
            context = value.context,
            requiresSettings = value.requiresSettings
        )
        encoder.encodeSerializableValue(CapabilitySurrogate.serializer(), surrogate)
    }

    override fun deserialize(decoder: Decoder): Capability {
        val input = decoder as? JsonDecoder ?: throw SerializationException("This serializer only supports JSON")
        val element = input.decodeJsonElement() as JsonObject
        val hasSemanticTypes = "semanticTypes" in element
        val finalElement = if (!hasSemanticTypes) {
            val legacySemanticType = element["semanticType"]?.jsonPrimitive?.contentOrNull
            val parsedList = parseSemanticTypes(legacySemanticType).map { type ->
                buildJsonObject {
                    put("namespace", type.namespace)
                    put("name", type.name)
                    put("variant", type.variant)
                }
            }
            JsonObject(element.filterKeys { it != "semanticType" } + ("semanticTypes" to JsonArray(parsedList)))
        } else {
            JsonObject(element.filterKeys { it != "semanticType" })
        }
        val surrogate = input.json.decodeFromJsonElement(CapabilitySurrogate.serializer(), finalElement)
        return Capability(
            name = surrogate.name,
            description = surrogate.description,
            parameters = surrogate.parameters,
            returnType = surrogate.returnType,
            semanticTypes = surrogate.semanticTypes,
            outputs = surrogate.outputs,
            isPausable = surrogate.isPausable,
            isCancellable = surrogate.isCancellable,
            context = surrogate.context,
            requiresSettings = surrogate.requiresSettings
        )
    }
}

@Serializable
@SerialName("Capability")
private class CapabilitySurrogate(
    val name: String,
    val description: String,
    val parameters: Map<String, ParameterMetadata>? = null,
    val returnType: DataType,
    val semanticTypes: List<SemanticType> = emptyList(),
    val outputs: List<OutputMetadata>? = null,
    val isPausable: Boolean = false,
    val isCancellable: Boolean = true,
    val context: CapabilityContext = CapabilityContext.ANY,
    val requiresSettings: List<String> = emptyList()
)

/**
 * Metadata for a custom action provided by the plugin.
 */
@Serializable
data class PluginAction(
    val name: String,
    val description: String,
    val functionName: String
)

