package org.wip.plugintoolkit.api

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.*

/**
 * Represents the type of data exchanged between the host and the plugin.
 */
@Serializable
sealed class DataType {
    /**
     * Checks if a value is "provided" for this data type.
     * This is used to validate required settings or parameters.
     * For example, a String is provided if it's not blank.
     * An Array is provided if it's not empty.
     */
    abstract fun isProvided(value: JsonElement?): Boolean

    /**
     * A basic primitive type (String, Int, Boolean, etc.).
     */
    @Serializable
    @SerialName("primitive")
    data class Primitive(val primitiveType: PrimitiveType) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            if (value == null || value is JsonNull) return false
            return when (primitiveType) {
                PrimitiveType.STRING -> (value as? JsonPrimitive)?.content?.isNotBlank() ?: false
                else -> true // Other primitives are provided if they exist
            }
        }
    }

    /**
     * A collection of items of the same type.
     */
    @Serializable
    @SerialName("array")
    data class Array(val items: DataType) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            if (value == null || value is JsonNull) return false
            return (value as? JsonArray)?.isNotEmpty() ?: true
        }
    }

    /**
     * A custom object type represented by its class name.
     */
    @Serializable
    @SerialName("object")
    data class Object(val className: String) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            return value != null && value !is JsonNull
        }
    }

    /**
     * An enumeration type with a set of predefined options.
     */
    @Serializable
    @SerialName("enum")
    data class Enum(val className: String, val options: List<String>) : DataType() {
        override fun isProvided(value: JsonElement?): Boolean {
            return value != null && value !is JsonNull
        }
    }
}

@Serializable
enum class PrimitiveType {
    DOUBLE, INT, STRING, BOOLEAN, UNIT, ANY
}


@Serializable
data class ParameterConstraints(
    val minValue: Double? = null,
    val maxValue: Double? = null,
    val minLength: Int? = null,
    val maxLength: Int? = null,
    val regex: String? = null,
    val multiSelect: Boolean? = null,
    val minChoices: Int? = null,
    val maxChoices: Int? = null
)

@Serializable
data class SettingMetadata(
    val defaultValue: JsonElement? = null,
    val description: String,
    val type: DataType,
    val required: Boolean = false,
    val secret: Boolean = false
)

/**
 * The complete manifest of a plugin, describing its capabilities and requirements.
 *
 * This object is typically generated by KSP and bundled with the plugin.
 */
@Serializable
data class PluginManifest(
    val manifestVersion: String,
    val plugin: PluginInfo,
    val requirements: Requirements,
    val defaultParameters: Map<String, ParameterMetadata>? = null,
    val capabilities: List<Capability> = emptyList(),
    val actions: List<PluginAction> = emptyList(),
    val settings: Map<String, SettingMetadata>? = null,
    val changelog: Changelog? = null,
    val hasUpdateHandler: Boolean = false,
    val hasSetupHandler: Boolean = false
)

@Serializable
data class Changelog(
    val releases: List<Release>
)

@Serializable
data class Release(
    val version: String,
    val date: String,
    val categories: Map<String, List<String>>
)

@Serializable
data class PluginInfo(
    val id: String,
    val name: String,
    val version: String,
    val description: String
)

@Serializable
data class Requirements(
    val minMemoryMb: Int,
    val minExecutionTimeMs: Int,
    val targetAppVersion: String? = ApiConfig.VERSION
)

@Serializable
data class ParameterMetadata(
    val defaultValue: JsonElement? = null,
    val description: String,
    val type: DataType,
    val constraints: ParameterConstraints? = null,
    val required: Boolean = false,
    val secret: Boolean = false
)

/**
 * Metadata for a specific capability provided by the plugin.
 */
@Serializable
data class Capability(
    val name: String,
    val description: String,
    val parameters: Map<String, ParameterMetadata>? = null,
    val returnType: DataType,
    val isPausable: Boolean = false,
    val isCancellable: Boolean = true
)

/**
 * Metadata for a custom action provided by the plugin.
 */
@Serializable
data class PluginAction(
    val name: String,
    val description: String,
    val functionName: String
)
