package org.wip.plugintoolkit.features.plugin.viewmodel

import kotlinx.serialization.json.JsonPrimitive
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.PrimitiveType
import org.wip.plugintoolkit.api.SettingMetadata
import org.wip.plugintoolkit.features.plugin.logic.resolveAutogeneratedSettings
import kotlin.test.Test
import kotlin.test.assertEquals

class PluginSettingsAutogenerationTest {
    private val stringType = DataType.Primitive(PrimitiveType.STRING)
    private val metadata = mapOf(
        "input" to SettingMetadata(description = "Input", type = stringType),
        "output" to SettingMetadata(
            description = "Output",
            type = stringType,
            autogeneratedPattern = "{input.dir}/{input.nameWithoutExtension}.result"
        )
    )

    @Test
    fun `derived setting follows its dependency`() {
        val result = resolveAutogeneratedSettings(
            metadata = metadata,
            settings = mapOf("input" to JsonPrimitive("work/photo.png"))
        )

        assertEquals(JsonPrimitive("work/photo.result"), result["output"])
    }

    @Test
    fun `derived setting preserves the last explicit value when dependency is missing`() {
        val result = resolveAutogeneratedSettings(
            metadata = metadata,
            settings = mapOf("output" to JsonPrimitive("stale.result"))
        )

        assertEquals(JsonPrimitive("stale.result"), result["output"])
    }

    @Test
    fun `invalid generated value does not replace a valid persisted value`() {
        val numberType = DataType.Primitive(PrimitiveType.INT)
        val result = resolveAutogeneratedSettings(
            metadata = metadata + (
                "count" to SettingMetadata(
                    description = "Count",
                    type = numberType,
                    autogeneratedPattern = "{input.nameWithoutExtension}"
                )
            ),
            settings = mapOf(
                "input" to JsonPrimitive("photo.png"),
                "count" to JsonPrimitive(42)
            )
        )

        assertEquals(JsonPrimitive(42), result["count"])
    }
}
