package org.wip.plugintoolkit.api.processor

import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSNode
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.KSValueParameter
import com.google.devtools.ksp.symbol.Modifier
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.ksp.toTypeName
import org.wip.plugintoolkit.api.DataType
import org.wip.plugintoolkit.api.PrimitiveType
import org.wip.plugintoolkit.api.SemanticType
import org.wip.plugintoolkit.api.parseSemanticTypes

object GeneratorUtils {
    data class OutputInfo(
        val name: String,
        val originalName: String,
        val type: DataType,
        val typeName: TypeName,
        val description: String,
        val semanticTypes: List<SemanticType>,
        val isAdvanced: Boolean = false,
        val condition: org.wip.plugintoolkit.api.ConditionGroup? = null
    )

    data class UnpackedParameter(
        val name: String,
        val originalName: String,
        val ksType: KSType,
        val typeName: TypeName,
        val dataType: DataType,
        val description: String,
        val defaultValue: String,
        val constraints: org.wip.plugintoolkit.api.ParameterConstraints?,
        val required: Boolean,
        val secret: Boolean,
        val semanticTypes: List<SemanticType>,
        val role: org.wip.plugintoolkit.api.ParameterRole,
        val autogeneratedPattern: String?,
        val isDestructive: Boolean,
        val isAdvanced: Boolean,
        val condition: org.wip.plugintoolkit.api.ConditionGroup?,
        val originNode: KSNode
    )

    fun mapKSTypeToDataType(ksType: KSType, visited: Set<String> = emptySet()): DataType {
        val declaration = ksType.declaration
        val qualifiedName = declaration.qualifiedName?.asString() ?: ""

        return when (qualifiedName) {
            "kotlin.Double", "kotlin.Float" -> DataType.Primitive(PrimitiveType.DOUBLE)
            "kotlin.Int", "kotlin.Short", "kotlin.Byte", "kotlin.Long" -> DataType.Primitive(PrimitiveType.INT)
            "kotlin.String", "kotlin.Char" -> DataType.Primitive(PrimitiveType.STRING)
            "kotlin.Boolean" -> DataType.Primitive(PrimitiveType.BOOLEAN)
            "kotlin.Unit" -> DataType.Primitive(PrimitiveType.UNIT)
            "kotlinx.serialization.json.JsonElement", "kotlin.Any" -> DataType.Primitive(PrimitiveType.ANY)
            "kotlin.collections.List", "kotlin.collections.MutableList", "kotlin.collections.Set", "kotlin.collections.MutableSet" -> {
                val elementType = ksType.arguments.firstOrNull()?.type?.resolve()
                if (elementType != null) {
                    DataType.Array(mapKSTypeToDataType(elementType, visited))
                } else {
                    DataType.Primitive(PrimitiveType.ANY)
                }
            }

            "kotlin.collections.Map", "kotlin.collections.MutableMap" -> {
                val valueType = ksType.arguments.getOrNull(1)?.type?.resolve()
                if (valueType != null) {
                    DataType.MapType(mapKSTypeToDataType(valueType, visited))
                } else {
                    DataType.MapType(DataType.Primitive(PrimitiveType.ANY))
                }
            }

            else -> {
                if (declaration is KSClassDeclaration && declaration.classKind == ClassKind.ENUM_CLASS) {
                    val enumEntries = declaration.declarations
                        .filterIsInstance<KSClassDeclaration>()
                        .filter { it.classKind == ClassKind.ENUM_ENTRY }
                        .toList()
                    val options = enumEntries.map { it.simpleName.asString() }
                    val optionRequirements = enumEntries.associate { entry ->
                        val reqAnn =
                            entry.annotations.find { it.hasQualifiedName(ProcessorConstants.REQUIRES_SETTING_ANNOTATION) }
                        val settings =
                            (reqAnn?.arguments?.find { it.name?.asString() == "settings" }?.value as? List<*>)?.filterIsInstance<String>()
                                ?: emptyList()
                        entry.simpleName.asString() to settings
                    }.filter { it.value.isNotEmpty() }
                    val optionLockRequirements = enumEntries.associate { entry ->
                        val lockAnn =
                            entry.annotations.find { it.hasQualifiedName(ProcessorConstants.REQUIRES_LOCK_ANNOTATION) }
                        val locks =
                            (lockAnn?.arguments?.find { it.name?.asString() == "locks" }?.value as? List<*>)?.filterIsInstance<String>()
                                ?: emptyList()
                        entry.simpleName.asString() to locks
                    }.filter { it.value.isNotEmpty() }
                    DataType.Enum(qualifiedName, options, null, optionRequirements, optionLockRequirements)
                } else {
                    if (visited.contains(qualifiedName)) {
                        DataType.Object(qualifiedName)
                    } else {
                        val newVisited = visited + qualifiedName
                        val complexObjAnn =
                            declaration.annotations.find { it.hasQualifiedName(ProcessorConstants.COMPLEX_OBJECT_ANNOTATION) }
                        val annId = complexObjAnn?.arguments?.find { it.name?.asString() == "id" }?.value as? String
                        val annDesc =
                            complexObjAnn?.arguments?.find { it.name?.asString() == "description" }?.value as? String
                        val annVersion =
                            complexObjAnn?.arguments?.find { it.name?.asString() == "version" }?.value as? Int

                        val id = if (annId.isNullOrEmpty()) null else annId
                        val description = if (annDesc.isNullOrEmpty()) null else annDesc
                        val version = if (complexObjAnn != null) (annVersion ?: 1) else null

                        val properties = if (declaration is KSClassDeclaration) {
                            declaration.getAllProperties().associate { prop ->
                                prop.simpleName.asString() to mapKSTypeToDataType(prop.type.resolve(), newVisited)
                            }
                        } else emptyMap()
                        DataType.Object(qualifiedName, id, description, version, null, properties)
                    }
                }
            }
        }
    }

    fun KSAnnotation.hasQualifiedName(name: String): Boolean {
        return this.annotationType.resolve().declaration.qualifiedName?.asString() == name
    }

    fun generateDataTypeCode(dataType: DataType): com.squareup.kotlinpoet.CodeBlock {
        val cnDataType = com.squareup.kotlinpoet.ClassName("org.wip.plugintoolkit.api", "DataType")
        val cnPrimitiveType = com.squareup.kotlinpoet.ClassName("org.wip.plugintoolkit.api", "PrimitiveType")
        return when (dataType) {
            is DataType.Primitive -> com.squareup.kotlinpoet.CodeBlock.of(
                "%T(%T.%L)",
                cnDataType.nestedClass("Primitive"),
                cnPrimitiveType,
                dataType.primitiveType.name
            )

            is DataType.Array -> com.squareup.kotlinpoet.CodeBlock.of(
                "%T(%L)",
                cnDataType.nestedClass("Array"),
                generateDataTypeCode(dataType.items)
            )

            is DataType.MapType -> com.squareup.kotlinpoet.CodeBlock.of(
                "%T(%L)",
                cnDataType.nestedClass("MapType"),
                generateDataTypeCode(dataType.valueType)
            )

            is DataType.Enum -> {
                val optionsList = dataType.options.joinToString { "\"$it\"" }
                if (dataType.optionRequirements.isEmpty() && dataType.optionLockRequirements.isEmpty()) {
                    com.squareup.kotlinpoet.CodeBlock.of(
                        "%T(%S, listOf(%L))",
                        cnDataType.nestedClass("Enum"),
                        dataType.className,
                        optionsList
                    )
                } else {
                    val reqMapStr = if (dataType.optionRequirements.isNotEmpty()) {
                        "mapOf(" + dataType.optionRequirements.entries.joinToString(", ") { entry ->
                            "\"${entry.key}\" to listOf(${entry.value.joinToString { "\"$it\"" }})"
                        } + ")"
                    } else "emptyMap()"
                    
                    val lockReqMapStr = if (dataType.optionLockRequirements.isNotEmpty()) {
                        "mapOf(" + dataType.optionLockRequirements.entries.joinToString(", ") { entry ->
                            "\"${entry.key}\" to listOf(${entry.value.joinToString { "\"$it\"" }})"
                        } + ")"
                    } else "emptyMap()"

                    com.squareup.kotlinpoet.CodeBlock.of(
                        "%T(%S, listOf(%L), null, %L, %L)",
                        cnDataType.nestedClass("Enum"),
                        dataType.className,
                        optionsList,
                        reqMapStr,
                        lockReqMapStr
                    )
                }
            }

            is DataType.Object -> {
                val idStr = dataType.id?.let { "\"$it\"" } ?: "null"
                val descStr = dataType.description?.let { "\"$it\"" } ?: "null"
                val verStr = dataType.version?.toString() ?: "null"

                if (dataType.properties.isEmpty()) {
                    com.squareup.kotlinpoet.CodeBlock.of(
                        "%T(%S, %L, %L, %L)",
                        cnDataType.nestedClass("Object"),
                        dataType.className,
                        idStr, descStr, verStr
                    )
                } else {
                    val propsCode = com.squareup.kotlinpoet.CodeBlock.builder()
                    propsCode.add("mapOf(\n")
                    propsCode.indent()
                    val entries = dataType.properties.entries.toList()
                    entries.forEachIndexed { index, entry ->
                        propsCode.add("%S to %L", entry.key, generateDataTypeCode(entry.value))
                        if (index < entries.size - 1) propsCode.add(",\n") else propsCode.add("\n")
                    }
                    propsCode.unindent()
                    propsCode.add(")")
                    com.squareup.kotlinpoet.CodeBlock.of(
                        "%T(%S, %L, %L, %L, null, %L)",
                        cnDataType.nestedClass("Object"),
                        dataType.className,
                        idStr, descStr, verStr,
                        propsCode.build()
                    )
                }
            }

            is DataType.Unknown -> com.squareup.kotlinpoet.CodeBlock.of(
                "%T(%S)",
                cnDataType.nestedClass("Unknown"),
                dataType.rawType
            )
        }
    }

    fun getCapabilityOutputs(func: KSFunctionDeclaration): List<OutputInfo> {
        val returnTypeKS = func.returnType?.resolve() ?: return emptyList()
        val returnTypeName = returnTypeKS.toTypeName()

        if (returnTypeName.toString() == "kotlin.Unit") {
            return emptyList()
        }

        val funcOutputAnn = func.annotations.find {
            it.hasQualifiedName(ProcessorConstants.CAPABILITY_RESULT_ANNOTATION)
        }

        if (funcOutputAnn != null) {
            val name = funcOutputAnn.arguments.find { it.name?.asString() == "name" }?.value as? String ?: ""
            val desc = funcOutputAnn.arguments.find { it.name?.asString() == "description" }?.value as? String ?: ""
            val semTypesVal =
                (funcOutputAnn.arguments.find { it.name?.asString() == "semanticTypes" }?.value as? List<*>)?.filterIsInstance<String>()
                    ?: emptyList()
            val semanticTypesList = semTypesVal.flatMap { parseSemanticTypes(it) }
            val isAdvanced = funcOutputAnn.arguments.find { it.name?.asString() == "isAdvanced" }?.value as? Boolean ?: false
            val conditionGroup = extractConditionGroup(func)
            return listOf(
                OutputInfo(
                    name = name.ifEmpty { "result" },
                    originalName = "result",
                    type = mapKSTypeToDataType(returnTypeKS),
                    typeName = returnTypeName,
                    description = desc,
                    semanticTypes = semanticTypesList,
                    isAdvanced = isAdvanced,
                    condition = conditionGroup
                )
            )
        }

        val declaration = returnTypeKS.declaration
        val isDataClass = declaration is KSClassDeclaration && declaration.modifiers.contains(Modifier.DATA)

        if (isDataClass) {
            val classDecl = declaration as KSClassDeclaration
            val properties = classDecl.getAllProperties().toList()
            val hasAnnotatedProperties = properties.any { prop ->
                prop.annotations.any { it.hasQualifiedName(ProcessorConstants.CAPABILITY_RESULT_ANNOTATION) }
            }

            if (hasAnnotatedProperties) {
                return properties.map { prop ->
                    val propAnn = prop.annotations.find {
                        it.hasQualifiedName(ProcessorConstants.CAPABILITY_RESULT_ANNOTATION)
                    }
                    val name = propAnn?.arguments?.find { it.name?.asString() == "name" }?.value as? String ?: ""
                    val desc = propAnn?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
                    val semTypesVal =
                        (propAnn?.arguments?.find { it.name?.asString() == "semanticTypes" }?.value as? List<*>)?.filterIsInstance<String>()
                            ?: emptyList()
                    val semanticTypesList = semTypesVal.flatMap { parseSemanticTypes(it) }
                    val propTypeKS = prop.type.resolve()
                    val isAdvanced = propAnn?.arguments?.find { it.name?.asString() == "isAdvanced" }?.value as? Boolean ?: false
                    val conditionGroup = extractConditionGroup(prop)

                    OutputInfo(
                        name = name.ifEmpty { prop.simpleName.asString() },
                        originalName = prop.simpleName.asString(),
                        type = mapKSTypeToDataType(propTypeKS),
                        typeName = propTypeKS.toTypeName(),
                        description = desc,
                        semanticTypes = semanticTypesList,
                        isAdvanced = isAdvanced,
                        condition = conditionGroup
                    )
                }
            }
        }

        // Default to a single "result" output
        return listOf(
            OutputInfo(
                name = "result",
                originalName = "result",
                type = mapKSTypeToDataType(returnTypeKS),
                typeName = returnTypeName,
                description = "",
                semanticTypes = emptyList(),
                isAdvanced = false,
                condition = null
            )
        )
    }

    fun parseDependsOnAnnotation(ann: KSAnnotation): org.wip.plugintoolkit.api.ParameterCondition {
        val param = ann.arguments.find { it.name?.asString() == "param" }?.value as? String ?: ""
        val setting = ann.arguments.find { it.name?.asString() == "setting" }?.value as? String ?: ""
        val lock = ann.arguments.find { it.name?.asString() == "lock" }?.value as? String ?: ""
        val opArg = ann.arguments.find { it.name?.asString() == "operator" }?.value
        val opName = when (opArg) {
            is com.google.devtools.ksp.symbol.KSClassDeclaration -> opArg.simpleName.asString()
            is KSType -> opArg.declaration.simpleName.asString()
            else -> opArg?.toString()?.substringAfterLast('.')?.substringAfterLast(':')?.trim() ?: "EQUALS"
        }
        val op = try {
            org.wip.plugintoolkit.api.ConditionOperator.valueOf(opName)
        } catch (e: Exception) {
            org.wip.plugintoolkit.api.ConditionOperator.EQUALS
        }
        val value = ann.arguments.find { it.name?.asString() == "value" }?.value as? String ?: ""
        val values = (ann.arguments.find { it.name?.asString() == "values" }?.value as? List<*>)
            ?.filterIsInstance<String>() ?: emptyList()

        val source = when {
            setting.isNotBlank() -> org.wip.plugintoolkit.api.ConditionSource.SETTING
            lock.isNotBlank() -> org.wip.plugintoolkit.api.ConditionSource.LOCK
            else -> org.wip.plugintoolkit.api.ConditionSource.PARAMETER
        }
        val target = when {
            setting.isNotBlank() -> setting
            lock.isNotBlank() -> lock
            else -> param
        }
        return org.wip.plugintoolkit.api.ParameterCondition(
            source = source,
            target = target,
            operator = op,
            value = value,
            values = values
        )
    }

    fun extractConditionGroup(annotated: com.google.devtools.ksp.symbol.KSAnnotated): org.wip.plugintoolkit.api.ConditionGroup? {
        val directDependsOn = annotated.annotations
            .filter { it.hasQualifiedName(ProcessorConstants.DEPENDS_ON_ANNOTATION) }
            .map { parseDependsOnAnnotation(it) }
            .toList()

        val dependsOnAnyAnn = annotated.annotations.find {
            it.hasQualifiedName(ProcessorConstants.DEPENDS_ON_ANY_ANNOTATION)
        }
        val dependsOnAllAnn = annotated.annotations.find {
            it.hasQualifiedName(ProcessorConstants.DEPENDS_ON_ALL_ANNOTATION)
        }

        if (dependsOnAnyAnn != null) {
            val nested = (dependsOnAnyAnn.arguments.find { it.name?.asString() == "conditions" }?.value as? List<*>)
                ?.filterIsInstance<KSAnnotation>()?.map { parseDependsOnAnnotation(it) } ?: emptyList()
            val allConditions = directDependsOn + nested
            if (allConditions.isNotEmpty()) {
                return org.wip.plugintoolkit.api.ConditionGroup(allConditions, isOr = true)
            }
        }

        if (dependsOnAllAnn != null) {
            val nested = (dependsOnAllAnn.arguments.find { it.name?.asString() == "conditions" }?.value as? List<*>)
                ?.filterIsInstance<KSAnnotation>()?.map { parseDependsOnAnnotation(it) } ?: emptyList()
            val allConditions = directDependsOn + nested
            if (allConditions.isNotEmpty()) {
                return org.wip.plugintoolkit.api.ConditionGroup(allConditions, isOr = false)
            }
        }

        if (directDependsOn.isNotEmpty()) {
            return org.wip.plugintoolkit.api.ConditionGroup(directDependsOn, isOr = false)
        }

        return null
    }

    fun generateConditionGroupCode(group: org.wip.plugintoolkit.api.ConditionGroup?): com.squareup.kotlinpoet.CodeBlock {
        if (group == null || group.conditions.isEmpty()) {
            return com.squareup.kotlinpoet.CodeBlock.of("null")
        }
        val cnGroup = ProcessorConstants.CN_CONDITION_GROUP
        val cnCondition = ProcessorConstants.CN_PARAMETER_CONDITION
        val cnSource = ProcessorConstants.CN_CONDITION_SOURCE
        val cnOperator = ProcessorConstants.CN_CONDITION_OPERATOR

        val builder = com.squareup.kotlinpoet.CodeBlock.builder()
        builder.add("%T(conditions = listOf(\n", cnGroup)
        builder.indent()
        group.conditions.forEachIndexed { index, cond ->
            val valuesListCode = if (cond.values.isEmpty()) {
                "emptyList()"
            } else {
                "listOf(" + cond.values.joinToString { "\"$it\"" } + ")"
            }
            builder.add(
                "%T(source = %T.%L, target = %S, operator = %T.%L, value = %S, values = %L)",
                cnCondition,
                cnSource,
                cond.source.name,
                cond.target,
                cnOperator,
                cond.operator.name,
                cond.value,
                valuesListCode
            )
            if (index < group.conditions.size - 1) builder.add(",\n") else builder.add("\n")
        }
        builder.unindent()
        builder.add("), isOr = %L)", group.isOr)
        return builder.build()
    }

    fun combineConditions(parent: org.wip.plugintoolkit.api.ConditionGroup?, child: org.wip.plugintoolkit.api.ConditionGroup?): org.wip.plugintoolkit.api.ConditionGroup? {
        if (parent == null || parent.conditions.isEmpty()) return child
        if (child == null || child.conditions.isEmpty()) return parent
        return org.wip.plugintoolkit.api.ConditionGroup(parent.conditions + child.conditions, isOr = false)
    }

    fun extractConstraints(ann: KSAnnotation?): org.wip.plugintoolkit.api.ParameterConstraints? {
        if (ann == null) return null
        val minValue = ann.arguments.find { it.name?.asString() == "minValue" }?.value as? Double ?: Double.NaN
        val maxValue = ann.arguments.find { it.name?.asString() == "maxValue" }?.value as? Double ?: Double.NaN
        val minLength = ann.arguments.find { it.name?.asString() == "minLength" }?.value as? Int ?: -1
        val maxLength = ann.arguments.find { it.name?.asString() == "maxLength" }?.value as? Int ?: -1
        val regex = ann.arguments.find { it.name?.asString() == "regex" }?.value as? String ?: ""
        val multiSelect = ann.arguments.find { it.name?.asString() == "multiSelect" }?.value as? Boolean ?: false
        val minChoices = ann.arguments.find { it.name?.asString() == "minChoices" }?.value as? Int ?: -1
        val maxChoices = ann.arguments.find { it.name?.asString() == "maxChoices" }?.value as? Int ?: -1

        val hasConstraints = !minValue.isNaN() || !maxValue.isNaN() || minLength != -1 || maxLength != -1 ||
                regex.isNotEmpty() || multiSelect || minChoices != -1 || maxChoices != -1
        if (!hasConstraints) return null

        return org.wip.plugintoolkit.api.ParameterConstraints(
            minValue = if (!minValue.isNaN()) minValue else null,
            maxValue = if (!maxValue.isNaN()) maxValue else null,
            minLength = if (minLength != -1) minLength else null,
            maxLength = if (maxLength != -1) maxLength else null,
            regex = regex.ifEmpty { null },
            multiSelect = if (multiSelect) true else null,
            minChoices = if (minChoices != -1) minChoices else null,
            maxChoices = if (maxChoices != -1) maxChoices else null
        )
    }

    fun getCapabilityParameters(
        func: KSFunctionDeclaration,
        logger: com.google.devtools.ksp.processing.KSPLogger? = null
    ): List<UnpackedParameter> {
        val result = mutableListOf<UnpackedParameter>()
        val seenNames = mutableMapOf<String, String>()

        fun remapConditionTargets(
            group: org.wip.plugintoolkit.api.ConditionGroup?,
            scopeMappings: Map<String, String>
        ): org.wip.plugintoolkit.api.ConditionGroup? {
            if (group == null || scopeMappings.isEmpty()) return group
            val remappedConditions = group.conditions.map { cond ->
                if (cond.source == org.wip.plugintoolkit.api.ConditionSource.PARAMETER) {
                    val mapped = if (scopeMappings.containsKey(cond.target)) {
                        scopeMappings[cond.target]!!
                    } else if (cond.target.contains('.')) {
                        val root = cond.target.substringBefore('.')
                        val rest = cond.target.substringAfter('.')
                        if (scopeMappings.containsKey(root)) {
                            "${scopeMappings[root]}$rest"
                        } else cond.target
                    } else {
                        cond.target
                    }
                    cond.copy(target = mapped)
                } else {
                    cond
                }
            }
            return group.copy(conditions = remappedConditions)
        }

        fun unpackParameterGroup(
            sourceNode: com.google.devtools.ksp.symbol.KSAnnotated,
            ksType: KSType,
            prefix: String,
            parentCondition: org.wip.plugintoolkit.api.ConditionGroup?,
            parentIsAdvanced: Boolean,
            visitedTypes: Set<String>,
            sourcePath: String,
            parentScope: Map<String, String> = emptyMap()
        ) {
            val declaration = ksType.declaration as? KSClassDeclaration ?: return
            val qualifiedName = declaration.qualifiedName?.asString() ?: declaration.simpleName.asString()

            if (visitedTypes.contains(qualifiedName)) {
                logger?.error(
                    "Recursive @ParameterGroup loop detected: ${visitedTypes.joinToString(" -> ")} -> $qualifiedName",
                    sourceNode
                )
                return
            }

            val isSerializable = declaration.annotations.any { it.shortName.asString() == "Serializable" }
            if (!isSerializable) {
                logger?.error(
                    "Class '$qualifiedName' used as @ParameterGroup in capability '${func.simpleName.asString()}' must be annotated with @Serializable.",
                    sourceNode
                )
            }

            val newVisited = visitedTypes + qualifiedName
            val properties = getSerializableProperties(declaration)

            val currentScope = parentScope.toMutableMap()
            for (prop in properties) {
                val propName = prop.simpleName.asString()
                val propTypeKS = prop.type.resolve()
                val isNested = prop.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) } ||
                        (propTypeKS.declaration.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) })
                if (isNested) {
                    val groupAnn = prop.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                        ?: propTypeKS.declaration.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                    val nestedPrefix = groupAnn?.arguments?.find { it.name?.asString() == "prefix" }?.value as? String ?: ""
                    currentScope[propName] = prefix + nestedPrefix
                } else {
                    currentScope[propName] = prefix + propName
                }
            }

            for (prop in properties) {
                val propTypeKS = prop.type.resolve()
                val isNestedGroup = prop.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) } ||
                        (propTypeKS.declaration.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) })

                if (isNestedGroup) {
                    val groupAnn = prop.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                        ?: propTypeKS.declaration.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                    val nestedPrefix = groupAnn?.arguments?.find { it.name?.asString() == "prefix" }?.value as? String ?: ""
                    val propCondition = extractConditionGroup(prop)
                    val remappedPropCondition = remapConditionTargets(propCondition, currentScope)
                    val mergedCondition = combineConditions(parentCondition, remappedPropCondition)
                    val propAnn = prop.annotations.find {
                        it.hasQualifiedName(ProcessorConstants.CAPABILITY_PARAM_ANNOTATION) ||
                        it.hasQualifiedName(ProcessorConstants.CAPABILITY_INPUT_ANNOTATION) ||
                        it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION)
                    }
                    val propIsAdvanced = propAnn?.arguments?.find { it.name?.asString() == "isAdvanced" }?.value as? Boolean ?: false
                    unpackParameterGroup(
                        sourceNode = prop,
                        ksType = propTypeKS,
                        prefix = prefix + nestedPrefix,
                        parentCondition = mergedCondition,
                        parentIsAdvanced = parentIsAdvanced || propIsAdvanced,
                        visitedTypes = newVisited,
                        sourcePath = "$sourcePath -> ${prop.simpleName.asString()}",
                        parentScope = currentScope
                    )
                } else {
                    val propName = prop.simpleName.asString()
                    val finalName = prefix + propName
                    val currentSource = "$sourcePath.$propName"

                    if (seenNames.containsKey(finalName)) {
                        logger?.error(
                            "Duplicate parameter name '$finalName' detected in capability '${func.simpleName.asString()}'. " +
                                    "It was defined by ${seenNames[finalName]} and also by '$currentSource'. " +
                                    "Use @ParameterGroup(prefix = \"...\") to namespace the parameter group, or rename the property.",
                            prop
                        )
                    } else {
                        seenNames[finalName] = currentSource
                    }

                    val paramAnn = prop.annotations.find {
                        it.hasQualifiedName(ProcessorConstants.CAPABILITY_PARAM_ANNOTATION) ||
                        it.hasQualifiedName(ProcessorConstants.CAPABILITY_INPUT_ANNOTATION) ||
                        it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION)
                    }
                    val paramDesc = paramAnn?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
                    val defaultValue = paramAnn?.arguments?.find { it.name?.asString() == "defaultValue" }?.value as? String ?: ""

                    val isInputLoc = prop.annotations.any { it.hasQualifiedName(ProcessorConstants.CAPABILITY_INPUT_ANNOTATION) }
                    val isOutputLoc = prop.annotations.any { it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION) }
                    val role = when {
                        isInputLoc -> org.wip.plugintoolkit.api.ParameterRole.INPUT_LOCATION
                        isOutputLoc -> org.wip.plugintoolkit.api.ParameterRole.OUTPUT_LOCATION
                        else -> org.wip.plugintoolkit.api.ParameterRole.STANDARD
                    }

                    val outputAnn = prop.annotations.find { it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION) }
                    val autogeneratedPattern = if (isOutputLoc) {
                        outputAnn?.arguments?.find { it.name?.asString() == "autogeneratedPattern" }?.value as? String
                    } else null
                    val isDestructive = if (isOutputLoc) {
                        outputAnn?.arguments?.find { it.name?.asString() == "isDestructive" }?.value as? Boolean ?: false
                    } else false

                    val isNullable = propTypeKS.isMarkedNullable
                    val explicitRequired = paramAnn?.arguments?.find { it.name?.asString() == "required" }?.value as? Boolean ?: false
                    val required = explicitRequired || (!isNullable && defaultValue.isEmpty())
                    val secret = paramAnn?.arguments?.find { it.name?.asString() == "secret" }?.value as? Boolean ?: false

                    val semTypesVal = (paramAnn?.arguments?.find { it.name?.asString() == "semanticTypes" }?.value as? List<*>)
                        ?.filterIsInstance<String>() ?: emptyList()
                    val semanticTypesList = semTypesVal.flatMap { parseSemanticTypes(it) }

                    val constraints = extractConstraints(paramAnn)
                    val propIsAdvanced = paramAnn?.arguments?.find { it.name?.asString() == "isAdvanced" }?.value as? Boolean ?: false
                    val isAdvanced = parentIsAdvanced || propIsAdvanced

                    val propCondition = extractConditionGroup(prop)
                    val remappedPropCondition = remapConditionTargets(propCondition, currentScope)
                    val condition = combineConditions(parentCondition, remappedPropCondition)

                    result.add(
                        UnpackedParameter(
                            name = finalName,
                            originalName = propName,
                            ksType = propTypeKS,
                            typeName = propTypeKS.toTypeName(),
                            dataType = mapKSTypeToDataType(propTypeKS),
                            description = paramDesc,
                            defaultValue = defaultValue,
                            constraints = constraints,
                            required = required,
                            secret = secret,
                            semanticTypes = semanticTypesList,
                            role = role,
                            autogeneratedPattern = if (autogeneratedPattern.isNullOrBlank()) null else autogeneratedPattern,
                            isDestructive = isDestructive,
                            isAdvanced = isAdvanced,
                            condition = condition,
                            originNode = prop
                        )
                    )
                }
            }
        }

        for (param in func.parameters) {
            val ksType = param.type.resolve()
            val paramType = ksType.toTypeName()

            if (ProcessorConstants.INFRASTRUCTURE_TYPES.contains(paramType)) continue
            if (param.annotations.any { it.hasQualifiedName(ProcessorConstants.RESUME_STATE_ANNOTATION) }) continue

            val isGroup = param.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) } ||
                    (ksType.declaration.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) })

            if (isGroup) {
                val groupAnn = param.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                    ?: ksType.declaration.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                val prefix = groupAnn?.arguments?.find { it.name?.asString() == "prefix" }?.value as? String ?: ""
                val groupCondition = extractConditionGroup(param)
                val paramAnn = param.annotations.find {
                    it.hasQualifiedName(ProcessorConstants.CAPABILITY_PARAM_ANNOTATION) ||
                    it.hasQualifiedName(ProcessorConstants.CAPABILITY_INPUT_ANNOTATION) ||
                    it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION)
                }
                val groupIsAdvanced = paramAnn?.arguments?.find { it.name?.asString() == "isAdvanced" }?.value as? Boolean ?: false
                val paramName = param.name?.asString() ?: "param"

                unpackParameterGroup(
                    sourceNode = param,
                    ksType = ksType,
                    prefix = prefix,
                    parentCondition = groupCondition,
                    parentIsAdvanced = groupIsAdvanced,
                    visitedTypes = emptySet(),
                    sourcePath = "ParameterGroup '$paramName'"
                )
            } else {
                val paramName = param.name?.asString() ?: ""
                val currentSource = "parameter '$paramName'"

                if (seenNames.containsKey(paramName)) {
                    logger?.error(
                        "Duplicate parameter name '$paramName' detected in capability '${func.simpleName.asString()}'. " +
                                "It was defined by ${seenNames[paramName]} and also by '$currentSource'.",
                        param
                    )
                } else {
                    seenNames[paramName] = currentSource
                }

                val paramAnn = param.annotations.find {
                    it.hasQualifiedName(ProcessorConstants.CAPABILITY_PARAM_ANNOTATION) ||
                    it.hasQualifiedName(ProcessorConstants.CAPABILITY_INPUT_ANNOTATION) ||
                    it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION)
                }
                val paramDesc = paramAnn?.arguments?.find { it.name?.asString() == "description" }?.value as? String ?: ""
                val defaultValue = paramAnn?.arguments?.find { it.name?.asString() == "defaultValue" }?.value as? String ?: ""

                val isInputLoc = param.annotations.any { it.hasQualifiedName(ProcessorConstants.CAPABILITY_INPUT_ANNOTATION) }
                val isOutputLoc = param.annotations.any { it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION) }
                val role = when {
                    isInputLoc -> org.wip.plugintoolkit.api.ParameterRole.INPUT_LOCATION
                    isOutputLoc -> org.wip.plugintoolkit.api.ParameterRole.OUTPUT_LOCATION
                    else -> org.wip.plugintoolkit.api.ParameterRole.STANDARD
                }

                val outputAnn = param.annotations.find { it.hasQualifiedName(ProcessorConstants.CAPABILITY_OUTPUT_ANNOTATION) }
                val autogeneratedPattern = if (isOutputLoc) {
                    outputAnn?.arguments?.find { it.name?.asString() == "autogeneratedPattern" }?.value as? String
                } else null
                val isDestructive = if (isOutputLoc) {
                    outputAnn?.arguments?.find { it.name?.asString() == "isDestructive" }?.value as? Boolean ?: false
                } else false

                val isNullable = ksType.isMarkedNullable
                val hasDefault = param.hasDefault
                val explicitRequired = paramAnn?.arguments?.find { it.name?.asString() == "required" }?.value as? Boolean ?: false
                val required = explicitRequired || (!isNullable && !hasDefault)
                val secret = paramAnn?.arguments?.find { it.name?.asString() == "secret" }?.value as? Boolean ?: false

                val semTypesVal = (paramAnn?.arguments?.find { it.name?.asString() == "semanticTypes" }?.value as? List<*>)
                    ?.filterIsInstance<String>() ?: emptyList()
                val semanticTypesList = semTypesVal.flatMap { parseSemanticTypes(it) }

                val constraints = extractConstraints(paramAnn)
                val isAdvanced = paramAnn?.arguments?.find { it.name?.asString() == "isAdvanced" }?.value as? Boolean ?: false
                val condition = extractConditionGroup(param)

                result.add(
                    UnpackedParameter(
                        name = paramName,
                        originalName = paramName,
                        ksType = ksType,
                        typeName = paramType,
                        dataType = mapKSTypeToDataType(ksType),
                        description = paramDesc,
                        defaultValue = defaultValue,
                        constraints = constraints,
                        required = required,
                        secret = secret,
                        semanticTypes = semanticTypesList,
                        role = role,
                        autogeneratedPattern = if (autogeneratedPattern.isNullOrBlank()) null else autogeneratedPattern,
                        isDestructive = isDestructive,
                        isAdvanced = isAdvanced,
                        condition = condition,
                        originNode = param
                    )
                )
            }
        }

        return result
    }

    private fun getSerializableProperties(
        declaration: com.google.devtools.ksp.symbol.KSClassDeclaration
    ): List<com.google.devtools.ksp.symbol.KSPropertyDeclaration> {
        val primaryParams = declaration.primaryConstructor?.parameters
        return if (!primaryParams.isNullOrEmpty()) {
            val allProps = declaration.getAllProperties().associateBy { it.simpleName.asString() }
            primaryParams.mapNotNull { p -> p.name?.asString()?.let { allProps[it] } }
        } else {
            declaration.getAllProperties().toList()
        }
    }

    fun generateDispatcherGroupJson(
        ksType: KSType,
        prefix: String = ""
    ): com.squareup.kotlinpoet.CodeBlock {
        val declaration = ksType.declaration as? KSClassDeclaration
            ?: return com.squareup.kotlinpoet.CodeBlock.of("%T()", com.squareup.kotlinpoet.ClassName("kotlinx.serialization.json", "JsonObject"))

        val builder = com.squareup.kotlinpoet.CodeBlock.builder()
        val cnBuildJsonObject = com.squareup.kotlinpoet.MemberName("kotlinx.serialization.json", "buildJsonObject")
        val cnPut = com.squareup.kotlinpoet.MemberName("kotlinx.serialization.json", "put")
        val cnJsonNull = com.squareup.kotlinpoet.ClassName("kotlinx.serialization.json", "JsonNull")

        builder.add("%M {\n", cnBuildJsonObject)
        builder.indent()

        for (prop in getSerializableProperties(declaration)) {
            val propName = prop.simpleName.asString()
            val propTypeKS = prop.type.resolve()
            val isNestedGroup = prop.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) } ||
                    (propTypeKS.declaration.annotations.any { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) })

            if (isNestedGroup) {
                val groupAnn = prop.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                    ?: propTypeKS.declaration.annotations.find { it.hasQualifiedName(ProcessorConstants.PARAMETER_GROUP_ANNOTATION) }
                val nestedPrefix = groupAnn?.arguments?.find { it.name?.asString() == "prefix" }?.value as? String ?: ""
                val nestedBlock = generateDispatcherGroupJson(propTypeKS, prefix + nestedPrefix)
                builder.add("%M(%S, %L)\n", cnPut, propName, nestedBlock)
            } else {
                val finalParamName = prefix + propName
                builder.add(
                    "request.parameters[%S]?.takeIf { it !is %T }?.let { %M(%S, it) }\n",
                    finalParamName,
                    cnJsonNull,
                    cnPut,
                    propName
                )
            }
        }

        builder.unindent()
        builder.add("}")
        return builder.build()
    }

    fun validateCapabilityConditions(
        capabilityName: String,
        parameters: Map<String, org.wip.plugintoolkit.api.ConditionGroup?>,
        availableSettings: Set<String>,
        logger: com.google.devtools.ksp.processing.KSPLogger,
        originNode: com.google.devtools.ksp.symbol.KSNode
    ) {
        val adj = mutableMapOf<String, MutableList<String>>()
        parameters.keys.forEach { adj[it] = mutableListOf() }

        parameters.forEach { (paramName, conditionGroup) ->
            conditionGroup?.conditions?.forEach { cond ->
                when (cond.source) {
                    org.wip.plugintoolkit.api.ConditionSource.PARAMETER -> {
                        val rootTarget = if (parameters.containsKey(cond.target)) cond.target else cond.target.substringBefore('.')
                        if (!parameters.containsKey(cond.target) && !parameters.containsKey(rootTarget)) {
                            logger.error(
                                "Parameter '$paramName' in capability '$capabilityName' depends on unknown parameter '${cond.target}'",
                                originNode
                            )
                        } else if (cond.target == paramName || rootTarget == paramName) {
                            logger.error(
                                "Parameter '$paramName' in capability '$capabilityName' cannot depend on itself",
                                originNode
                            )
                        } else {
                            adj[paramName]?.add(rootTarget)
                        }
                    }

                    org.wip.plugintoolkit.api.ConditionSource.SETTING -> {
                        val rootTarget = if (availableSettings.contains(cond.target)) cond.target else cond.target.substringBefore('.')
                        if (availableSettings.isNotEmpty() && !availableSettings.contains(cond.target) && !availableSettings.contains(rootTarget)) {
                            logger.error(
                                "Parameter '$paramName' in capability '$capabilityName' depends on unknown setting '${cond.target}'",
                                originNode
                            )
                        }
                    }

                    org.wip.plugintoolkit.api.ConditionSource.LOCK -> {
                        // Dynamic runtime check
                    }
                }
            }
        }

        // Cycle detection via DFS
        val visited = mutableSetOf<String>()
        val inStack = mutableSetOf<String>()
        val path = mutableListOf<String>()

        fun dfs(current: String): Boolean {
            visited.add(current)
            inStack.add(current)
            path.add(current)

            for (neighbor in adj[current] ?: emptyList()) {
                if (neighbor in inStack) {
                    val cycleStartIndex = path.indexOf(neighbor)
                    val cyclePath = path.subList(cycleStartIndex, path.size) + neighbor
                    logger.error(
                        "Circular parameter dependency detected in capability '$capabilityName': ${cyclePath.joinToString(" -> ")}",
                        originNode
                    )
                    return true
                }
                if (neighbor !in visited) {
                    if (dfs(neighbor)) return true
                }
            }

            path.removeAt(path.size - 1)
            inStack.remove(current)
            return false
        }

        for (param in parameters.keys) {
            if (param !in visited) {
                dfs(param)
            }
        }
    }
}

