package org.wip.plugintoolkit.standalone

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement
import androidx.compose.ui.window.WindowPosition
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState
import androidx.lifecycle.ViewModelStore
import androidx.lifecycle.ViewModelStoreOwner
import androidx.lifecycle.viewmodel.compose.LocalViewModelStoreOwner
import co.touchlab.kermit.Logger
import co.touchlab.kermit.Severity
import co.touchlab.kermit.platformLogWriter
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.launch
import org.jetbrains.compose.resources.painterResource
import org.koin.core.context.startKoin
import org.koin.core.qualifier.named
import org.koin.dsl.koinApplication
import org.koin.dsl.module
import org.koin.mp.KoinPlatform.getKoin
import org.wip.plugintoolkit.AppConfig
import org.wip.plugintoolkit.api.PluginEntry
import org.wip.plugintoolkit.api.PluginModuleProvider
import org.wip.plugintoolkit.core.DefaultSystemConfig
import org.wip.plugintoolkit.core.PortableSystemConfig
import org.wip.plugintoolkit.core.StandaloneSystemConfig
import org.wip.plugintoolkit.core.SystemConfig
import org.wip.plugintoolkit.core.coroutineModule
import org.wip.plugintoolkit.core.createStandaloneLogicModule
import org.wip.plugintoolkit.core.guiModule
import org.wip.plugintoolkit.core.theme.AppTheme
import org.wip.plugintoolkit.core.theme.ToolkitTheme
import org.wip.plugintoolkit.core.utils.PlatformLocalization
import org.wip.plugintoolkit.features.plugin.logic.PluginLoader
import org.wip.plugintoolkit.features.plugin.logic.PluginManager
import org.wip.plugintoolkit.features.plugin.logic.PluginRegistry
import org.wip.plugintoolkit.features.plugin.model.InstalledPlugin
import org.wip.plugintoolkit.features.plugin.ui.SinglePluginRunnerView
import org.wip.plugintoolkit.features.plugin.viewmodel.SinglePluginHostViewModel
import org.wip.plugintoolkit.features.settings.logic.SettingsRepository
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.app_logo
import java.awt.Dimension
import java.io.File
import java.util.ServiceLoader
import javax.swing.JOptionPane
import kotlin.system.exitProcess

private const val WINDOW_MIN_WIDTH = 750
private const val WINDOW_MIN_HEIGHT = 500

fun detectStandaloneSystemConfig(pluginId: String): SystemConfig {
    val userDir = File(System.getProperty("user.dir"))
    if (File(userDir, ".portable").exists()) {
        Logger.i { "Standalone Runner: Portable marker found in user.dir (${userDir.absolutePath})" }
        return StandaloneSystemConfig(pluginId = pluginId, baseDir = userDir.absolutePath)
    }
    return StandaloneSystemConfig(pluginId = pluginId)
}

fun discoverPluginEntry(args: Array<String>): PluginEntry {
    // 1. Check CLI flag, system property, or direct .jar path argument for dynamic JAR loading
    val jarArgIndex = args.indexOf("--plugin-jar")
    val jarPath = if (jarArgIndex != -1 && jarArgIndex + 1 < args.size) {
        args[jarArgIndex + 1]
    } else {
        System.getProperty("plugin.jar") ?: args.firstOrNull { it.endsWith(".jar") && !it.startsWith("-") }
    }

    if (!jarPath.isNullOrBlank()) {
        Logger.i { "Standalone Runner: Loading plugin from JAR at $jarPath" }
        val loaded = PluginLoader.loadPlugin(jarPath)
        if (loaded.isSuccess) {
            val entry = loaded.getOrThrow()
            PluginLoader.registerPlugin(entry)
            return entry
        } else {
            Logger.e { "Standalone Runner: Failed to load plugin from $jarPath: ${loaded.exceptionOrNull()?.message}" }
        }
    }

    // 2. Discover via PluginModuleProvider (generated by KSP in META-INF/services)
    val moduleLoader = ServiceLoader.load(PluginModuleProvider::class.java)
    val moduleProvider = moduleLoader.firstOrNull()
    if (moduleProvider != null) {
        Logger.i { "Standalone Runner: Discovered PluginModuleProvider via ServiceLoader: ${moduleProvider::class.qualifiedName}" }
        try {
            val pluginModule = moduleProvider.getKoinModule(emptyMap())
            val koinApp = koinApplication {
                modules(pluginModule)
            }
            val entry = koinApp.koin.getOrNull<PluginEntry>()
            if (entry != null) {
                PluginLoader.registerPlugin(entry)
                return entry
            }
        } catch (t: Throwable) {
            Logger.w(t) { "Failed to resolve PluginEntry from PluginModuleProvider" }
        }
    }

    // 3. Discover via PluginEntry directly (if registered via ServiceLoader)
    val serviceLoader = ServiceLoader.load(PluginEntry::class.java)
    val entry = serviceLoader.firstOrNull()
    if (entry != null) {
        Logger.i { "Standalone Runner: Discovered PluginEntry via ServiceLoader: ${entry::class.qualifiedName}" }
        PluginLoader.registerPlugin(entry)
        return entry
    }

    // 4. Fallback: check already registered plugins in PluginLoader
    val registered = PluginLoader.getPlugins().firstOrNull()
    if (registered != null) {
        return registered
    }

    throw IllegalStateException(
        "No PluginEntry found. Please ensure a plugin is on the classpath or specify --plugin-jar <path>."
    )
}

fun main(args: Array<String>) {
    Logger.setLogWriters(platformLogWriter())
    Logger.setMinSeverity(Severity.Debug)
    Logger.i { "Starting Standalone Plugin Runner" }

    val pluginEntry = try {
        discoverPluginEntry(args)
    } catch (e: Throwable) {
        e.printStackTrace()
        JOptionPane.showMessageDialog(
            null,
            "Failed to locate plugin entry point:\n${e.message}\n\nMake sure the plugin dependency is bundled or provided via --plugin-jar.",
            "Plugin Runner Error",
            JOptionPane.ERROR_MESSAGE
        )
        exitProcess(1)
    }

    val manifest = pluginEntry.getManifest().getOrThrow()
    val pluginId = manifest.plugin.id

    val detectedConfig = detectStandaloneSystemConfig(pluginId)

    startKoin {
        modules(
            coroutineModule,
            createStandaloneLogicModule(),
            guiModule,
            module {
                single<SystemConfig> { detectedConfig }
                single<PluginEntry> { pluginEntry }
            }
        )
    }

    val koin = getKoin()
    val settingsRepository = koin.get<SettingsRepository>()
    val pluginRegistry = koin.get<PluginRegistry>()
    val pluginManager = koin.get<PluginManager>()
    val appScope = koin.get<CoroutineScope>(named("AppScope"))

    // Ensure plugin is registered directly in PluginLoader with current working directory
    PluginLoader.registerPlugin(pluginEntry, System.getProperty("user.dir"))

    // Register InstalledPlugin record so pluginManager.installedPlugins observes it
    val installed = InstalledPlugin(
        pkg = pluginId,
        name = manifest.plugin.name,
        version = manifest.plugin.version,
        installPath = System.getProperty("user.dir"),
        isEnabled = true,
        isValidated = true,
        isSetupCompleted = !manifest.hasSetupHandler,
        description = manifest.plugin.description,
        targetAppVersion = manifest.requirements.targetAppVersion ?: AppConfig.VERSION,
        supportedOs = manifest.plugin.supportedOs
    )

    appScope.launch {
        pluginRegistry.updatePlugins { listOf(installed) }
        try {
            val loadResult = pluginManager.loadPlugin(pluginId)
            if (loadResult.isFailure) {
                Logger.w { "Standalone loadPlugin reported failure: ${loadResult.exceptionOrNull()?.message}, falling back to direct context initialization" }
                pluginEntry.initialize(pluginManager.createPluginContext(pluginId, manifest = manifest))
                pluginEntry.performLoad(pluginManager.createPluginContext(pluginId, manifest = manifest))
            } else {
                Logger.i { "Plugin $pluginId initialized and loaded successfully in standalone host." }
            }
        } catch (t: Throwable) {
            Logger.e(t) { "Error during standalone initialization of plugin $pluginId" }
        }
    }

    application {
        val appSettings by settingsRepository.settings.collectAsState()
        val languageCode = if (appSettings.localization.useSystemLanguage) {
            val systemLang = PlatformLocalization.getSystemLanguage()
            if (systemLang == "it") "it" else "en"
        } else {
            when (appSettings.localization.language) {
                org.wip.plugintoolkit.features.settings.model.AppLanguage.Italian -> "it"
                org.wip.plugintoolkit.features.settings.model.AppLanguage.English -> "en"
            }
        }
        PlatformLocalization.setApplicationLanguage(languageCode)

        val viewModelStoreOwner = remember {
            object : ViewModelStoreOwner {
                override val viewModelStore = ViewModelStore()
            }
        }

        DisposableEffect(Unit) {
            onDispose {
                viewModelStoreOwner.viewModelStore.clear()
            }
        }

        val windowState = rememberWindowState(
            placement = WindowPlacement.Floating,
            position = WindowPosition(Alignment.Center),
            size = DpSize(ToolkitTheme.dimensions.dialogMaxWidth, ToolkitTheme.dimensions.dialogMaxHeight)
        )

        Window(
            onCloseRequest = { exitApplication() },
            title = "${manifest.plugin.name} (v${manifest.plugin.version}) - Plugin Runner",
            icon = painterResource(Res.drawable.app_logo),
            state = windowState
        ) {
            window.minimumSize = Dimension(WINDOW_MIN_WIDTH, WINDOW_MIN_HEIGHT)

            AppTheme(appearance = appSettings.appearance) {
                Box(modifier = Modifier.fillMaxSize()) {
                    CompositionLocalProvider(
                        LocalViewModelStoreOwner provides viewModelStoreOwner
                    ) {
                        SinglePluginRunnerView()
                    }
                }
            }
        }
    }
}
