package org.wip.plugintoolkit.shared.components.plugin

import androidx.compose.runtime.Composable
import kotlinx.serialization.json.JsonElement
import org.koin.compose.koinInject
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.core.utils.SemanticCategory
import org.wip.plugintoolkit.core.utils.SemanticRegistry
import org.wip.plugintoolkit.shared.components.plugin.inputs.ColorInput
import org.wip.plugintoolkit.shared.components.plugin.inputs.EnumDropdownInput
import org.wip.plugintoolkit.shared.components.plugin.inputs.FileInput
import org.wip.plugintoolkit.shared.components.plugin.inputs.PrimitiveInput

@Composable
fun DynamicParameterInput(
    name: String,
    metadata: ParameterMetadata,
    value: String,
    onValueChange: (String) -> Unit,
    enabled: Boolean = true,
    isAutoGenerated: Boolean = false,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    compact: Boolean = false
) {
    val semanticRegistry = koinInject<SemanticRegistry>()
    val category = semanticRegistry.getCategory(metadata.semanticTypes)
        ?: when (metadata.role) {
            org.wip.plugintoolkit.api.ParameterRole.INPUT_LOCATION, org.wip.plugintoolkit.api.ParameterRole.OUTPUT_LOCATION -> SemanticCategory.FILE
            else -> null
        }

    when (category) {
        SemanticCategory.IMAGE, SemanticCategory.AUDIO, SemanticCategory.VIDEO, SemanticCategory.FILE, SemanticCategory.PATH -> {
            FileInput(name, metadata, value, onValueChange, category, enabled, isAutoGenerated, compact)
        }

        SemanticCategory.COLOR -> {
            ColorInput(name, metadata, value, onValueChange, enabled, isAutoGenerated, compact)
        }

        else -> {
            if ((metadata.type as? org.wip.plugintoolkit.api.DataType.Enum)?.options?.isNotEmpty() == true) {
                EnumDropdownInput(
                    name,
                    metadata,
                    value,
                    onValueChange,
                    enabled,
                    isAutoGenerated,
                    providedSettings,
                    compact
                )
            } else {
                PrimitiveInput(name, metadata, value, onValueChange, enabled, isAutoGenerated, compact)
            }
        }
    }
}
