package org.wip.plugintoolkit.shared.components.plugin

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.jetbrains.compose.resources.stringResource
import org.wip.plugintoolkit.api.FileAccess
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.ParameterRole
import org.wip.plugintoolkit.core.theme.ToolkitTheme
import org.wip.plugintoolkit.shared.components.GlassCard
import org.wip.plugintoolkit.shared.components.SectionHeader
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.plugin_save_results

data class ExecutionParameter(
    val name: String,
    val value: String,
    val metadata: ParameterMetadata,
    val onValueChange: (String) -> Unit,
    val enabled: Boolean = true,
    val isAutoGenerated: Boolean = false
)

@Composable
fun ExecutionParametersCard(
    title: String,
    icon: ImageVector,
    description: String?,
    fileAccess: FileAccess?,
    isDestructive: Boolean,
    saveResults: Boolean,
    onSaveResultsChange: (Boolean) -> Unit,
    parameters: List<ExecutionParameter>,
    modifier: Modifier = Modifier
) {
    GlassCard(modifier = modifier.fillMaxWidth()) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                SectionHeader(
                    title = title,
                    icon = icon
                )
                if (fileAccess != null && (fileAccess.readsFiles || fileAccess.writesFiles || fileAccess.isDestructive)) {
                    Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
                    FileAccessChips(fileAccess = fileAccess)
                }
            }

            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(
                    stringResource(Res.string.plugin_save_results),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.outline
                )
                Spacer(modifier = Modifier.width(8.dp))
                Switch(
                    checked = saveResults,
                    onCheckedChange = onSaveResultsChange,
                    modifier = Modifier.scale(0.8f)
                )
            }
        }

        if (!description.isNullOrEmpty()) {
            Spacer(modifier = Modifier.height(ToolkitTheme.spacing.medium))
            Text(
                description,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        if (isDestructive) {
            Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
            Surface(
                modifier = Modifier.fillMaxWidth(),
                color = MaterialTheme.colorScheme.errorContainer,
                shape = MaterialTheme.shapes.small
            ) {
                Text(
                    "Warning: This operation performs destructive file operations (like overriding or deleting files).",
                    color = MaterialTheme.colorScheme.onErrorContainer,
                    modifier = Modifier.padding(ToolkitTheme.spacing.medium),
                    style = MaterialTheme.typography.labelMedium
                )
            }
        }

        Spacer(modifier = Modifier.height(ToolkitTheme.spacing.large))

        if (parameters.isNotEmpty()) {
            val standardParams = parameters.filter { it.metadata.role == ParameterRole.STANDARD }
            val inputParams = parameters.filter { it.metadata.role == ParameterRole.INPUT_LOCATION }
            val outputParams = parameters.filter { it.metadata.role == ParameterRole.OUTPUT_LOCATION }

            if (standardParams.isNotEmpty()) {
                ParameterGroup(
                    title = "Execution Inputs",
                    parameters = standardParams
                )
            }

            if (inputParams.isNotEmpty()) {
                ParameterGroup(
                    title = "Input Locations",
                    parameters = inputParams
                )
            }

            if (outputParams.isNotEmpty()) {
                ParameterGroup(
                    title = "Output Locations",
                    parameters = outputParams
                )
            }
        }
    }
}

@Composable
private fun ParameterGroup(title: String, parameters: List<ExecutionParameter>) {
    Text(
        title,
        style = MaterialTheme.typography.titleMedium,
        fontWeight = FontWeight.Bold,
        color = MaterialTheme.colorScheme.primary,
        modifier = Modifier.padding(vertical = ToolkitTheme.spacing.small)
    )
    Surface(
        modifier = Modifier.fillMaxWidth(),
        color = MaterialTheme.colorScheme.surface,
        shape = RoundedCornerShape(8.dp),
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant)
    ) {
        Column(
            modifier = Modifier.padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(ToolkitTheme.spacing.medium)
        ) {
            parameters.forEach { param ->
                DynamicParameterInput(
                    name = param.name,
                    metadata = param.metadata,
                    value = param.value,
                    onValueChange = param.onValueChange,
                    enabled = param.enabled,
                    isAutoGenerated = param.isAutoGenerated
                )
            }
        }
    }
    Spacer(modifier = Modifier.height(16.dp))
}
