package org.wip.plugintoolkit.shared.components.plugin

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlinx.serialization.json.JsonElement
import org.jetbrains.compose.resources.stringResource
import org.wip.plugintoolkit.api.FileAccess
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.ParameterRole
import org.wip.plugintoolkit.core.theme.ToolkitTheme
import org.wip.plugintoolkit.shared.components.GlassCard
import org.wip.plugintoolkit.shared.components.SectionHeader
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.plugin_destructive_warning
import plugintoolkit.composeapp.generated.resources.plugin_execution_inputs
import plugintoolkit.composeapp.generated.resources.plugin_input_locations
import plugintoolkit.composeapp.generated.resources.plugin_output_locations
import plugintoolkit.composeapp.generated.resources.plugin_save_results

data class ExecutionParameter(
    val name: String,
    val value: String,
    val metadata: ParameterMetadata,
    val onValueChange: (String) -> Unit,
    val enabled: Boolean = true,
    val isAutoGenerated: Boolean = false,
    val pluginId: String = ""
)

@Composable
fun ExecutionParametersCard(
    title: String,
    icon: ImageVector,
    description: String?,
    fileAccess: FileAccess?,
    isDestructive: Boolean,
    saveResults: Boolean,
    onSaveResultsChange: (Boolean) -> Unit,
    parameters: List<ExecutionParameter>,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    providedLocks: Map<String, Boolean> = emptyMap(),
    hasUnsavedChanges: Boolean = false,
    pluginId: String = "",
    onNavigateToPluginSetting: ((pluginId: String, settingKey: String) -> Unit)? = null,
    modifier: Modifier = Modifier
) {
    GlassCard(modifier = modifier.fillMaxWidth()) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                SectionHeader(
                    title = title,
                    icon = icon
                )
                if (fileAccess != null && (fileAccess.readsFiles || fileAccess.writesFiles || fileAccess.isDestructive)) {
                    Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
                    FileAccessChips(fileAccess = fileAccess)
                }
            }

            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(
                    stringResource(Res.string.plugin_save_results),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                Spacer(modifier = Modifier.width(ToolkitTheme.spacing.small))
                Switch(
                    checked = saveResults,
                    onCheckedChange = onSaveResultsChange,
                    modifier = Modifier.scale(0.8f)
                )
            }
        }

        if (!description.isNullOrBlank()) {
            Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
            Text(
                description,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        if (isDestructive) {
            Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
            Surface(
                modifier = Modifier.fillMaxWidth(),
                color = MaterialTheme.colorScheme.errorContainer,
                shape = MaterialTheme.shapes.small
            ) {
                Text(
                    stringResource(Res.string.plugin_destructive_warning),
                    color = MaterialTheme.colorScheme.onErrorContainer,
                    modifier = Modifier.padding(ToolkitTheme.spacing.medium),
                    style = MaterialTheme.typography.labelMedium
                )
            }
        }

        Spacer(modifier = Modifier.height(ToolkitTheme.spacing.large))

        if (parameters.isNotEmpty()) {
            val standardParams = parameters.filter { it.metadata.role == ParameterRole.STANDARD }
            val inputParams = parameters.filter { it.metadata.role == ParameterRole.INPUT_LOCATION }
            val outputParams = parameters.filter { it.metadata.role == ParameterRole.OUTPUT_LOCATION }

            if (standardParams.isNotEmpty()) {
                ParameterGroup(
                    title = stringResource(Res.string.plugin_execution_inputs),
                    parameters = standardParams,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = pluginId,
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }

            if (inputParams.isNotEmpty()) {
                ParameterGroup(
                    title = stringResource(Res.string.plugin_input_locations),
                    parameters = inputParams,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = pluginId,
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }

            if (outputParams.isNotEmpty()) {
                ParameterGroup(
                    title = stringResource(Res.string.plugin_output_locations),
                    parameters = outputParams,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = pluginId,
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }
        }
    }
}

@Composable
private fun ParameterGroup(
    title: String,
    parameters: List<ExecutionParameter>,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    providedLocks: Map<String, Boolean> = emptyMap(),
    hasUnsavedChanges: Boolean = false,
    pluginId: String = "",
    onNavigateToPluginSetting: ((pluginId: String, settingKey: String) -> Unit)? = null
) {
    Text(
        title,
        style = MaterialTheme.typography.titleMedium,
        fontWeight = FontWeight.Bold,
        color = MaterialTheme.colorScheme.primary,
        modifier = Modifier.padding(vertical = ToolkitTheme.spacing.small)
    )
    Surface(
        modifier = Modifier.fillMaxWidth(),
        color = MaterialTheme.colorScheme.surface,
        shape = ToolkitTheme.shapes.small,
        border = BorderStroke(ToolkitTheme.dimensions.borderUnselected, MaterialTheme.colorScheme.outlineVariant)
    ) {
        Column(
            modifier = Modifier.padding(ToolkitTheme.spacing.medium),
            verticalArrangement = Arrangement.spacedBy(ToolkitTheme.spacing.medium)
        ) {
            parameters.forEach { param ->
                DynamicParameterInput(
                    name = param.name,
                    metadata = param.metadata,
                    value = param.value,
                    onValueChange = param.onValueChange,
                    enabled = param.enabled,
                    isAutoGenerated = param.isAutoGenerated,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = param.pluginId.ifBlank { pluginId },
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }
        }
    }
    Spacer(modifier = Modifier.height(ToolkitTheme.spacing.medium))
}
