package org.wip.plugintoolkit.shared.components.plugin

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.expandVertically
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.shrinkVertically
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ExpandLess
import androidx.compose.material.icons.filled.ExpandMore
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import kotlinx.serialization.json.JsonElement
import org.jetbrains.compose.resources.stringResource
import org.wip.plugintoolkit.api.FileAccess
import org.wip.plugintoolkit.api.ParameterMetadata
import org.wip.plugintoolkit.api.ParameterRole
import org.wip.plugintoolkit.core.theme.ToolkitTheme
import org.wip.plugintoolkit.features.plugin.logic.ParameterDependencyGraph
import org.wip.plugintoolkit.shared.components.ToolkitCard
import org.wip.plugintoolkit.shared.components.SectionHeader
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.action_hide_advanced
import plugintoolkit.composeapp.generated.resources.action_show_advanced
import plugintoolkit.composeapp.generated.resources.advanced_parameters_section
import plugintoolkit.composeapp.generated.resources.plugin_destructive_warning
import plugintoolkit.composeapp.generated.resources.plugin_execution_inputs
import plugintoolkit.composeapp.generated.resources.plugin_input_locations
import plugintoolkit.composeapp.generated.resources.plugin_output_locations
import plugintoolkit.composeapp.generated.resources.plugin_save_results

data class ExecutionParameter(
    val name: String,
    val value: String,
    val metadata: ParameterMetadata,
    val onValueChange: (String) -> Unit,
    val enabled: Boolean = true,
    val isAutoGenerated: Boolean = false,
    val pluginId: String = ""
)

@Composable
fun ExecutionParametersCard(
    title: String,
    icon: ImageVector,
    description: String?,
    fileAccess: FileAccess?,
    isDestructive: Boolean,
    saveResults: Boolean,
    onSaveResultsChange: (Boolean) -> Unit,
    parameters: List<ExecutionParameter>,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    providedLocks: Map<String, Boolean> = emptyMap(),
    hasUnsavedChanges: Boolean = false,
    pluginId: String = "",
    onNavigateToPluginSetting: ((pluginId: String, settingKey: String) -> Unit)? = null,
    modifier: Modifier = Modifier
) {
    var showAdvanced by rememberSaveable { mutableStateOf(false) }

    ToolkitCard(modifier = modifier.fillMaxWidth()) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                SectionHeader(
                    title = title,
                    icon = icon
                )
                if (fileAccess != null && (fileAccess.readsFiles || fileAccess.writesFiles || fileAccess.isDestructive)) {
                    Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
                    FileAccessChips(fileAccess = fileAccess)
                }
            }

            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(
                    stringResource(Res.string.plugin_save_results),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                Spacer(modifier = Modifier.width(ToolkitTheme.spacing.small))
                Switch(
                    checked = saveResults,
                    onCheckedChange = onSaveResultsChange,
                    modifier = Modifier.scale(0.8f)
                )
            }
        }

        if (!description.isNullOrBlank()) {
            Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
            Text(
                description,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        if (isDestructive) {
            Spacer(modifier = Modifier.height(ToolkitTheme.spacing.small))
            Surface(
                modifier = Modifier.fillMaxWidth(),
                color = MaterialTheme.colorScheme.errorContainer,
                shape = MaterialTheme.shapes.small
            ) {
                Text(
                    stringResource(Res.string.plugin_destructive_warning),
                    color = MaterialTheme.colorScheme.onErrorContainer,
                    modifier = Modifier.padding(ToolkitTheme.spacing.medium),
                    style = MaterialTheme.typography.labelMedium
                )
            }
        }

        Spacer(modifier = Modifier.height(ToolkitTheme.spacing.large))

        if (parameters.isNotEmpty()) {
            val currentParamElements = remember(parameters) {
                parameters.associate {
                    it.name to org.wip.plugintoolkit.features.flows.model.NodeSerializationUtils.anyToJsonElement(it.value)
                }
            }
            val paramMap = remember(parameters) { parameters.associate { it.name to it.metadata } }
            val activeParamNames = remember(paramMap, currentParamElements, providedSettings, providedLocks) {
                ParameterDependencyGraph.computeActiveParameters(
                    parameters = paramMap,
                    values = currentParamElements,
                    settings = providedSettings,
                    locks = providedLocks
                )
            }

            val activeParams = parameters.filter { it.name in activeParamNames }
            val normalParams = activeParams.filter { !it.metadata.isAdvanced }
            val advancedParams = activeParams.filter { it.metadata.isAdvanced }

            val standardParams = normalParams.filter { it.metadata.role == ParameterRole.STANDARD }
            val inputParams = normalParams.filter { it.metadata.role == ParameterRole.INPUT_LOCATION }
            val outputParams = normalParams.filter { it.metadata.role == ParameterRole.OUTPUT_LOCATION }

            if (standardParams.isNotEmpty()) {
                ParameterGroup(
                    title = stringResource(Res.string.plugin_execution_inputs),
                    parameters = standardParams,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = pluginId,
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }

            if (inputParams.isNotEmpty()) {
                ParameterGroup(
                    title = stringResource(Res.string.plugin_input_locations),
                    parameters = inputParams,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = pluginId,
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }

            if (outputParams.isNotEmpty()) {
                ParameterGroup(
                    title = stringResource(Res.string.plugin_output_locations),
                    parameters = outputParams,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = pluginId,
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }

            if (advancedParams.isNotEmpty()) {
                OutlinedButton(
                    onClick = { showAdvanced = !showAdvanced },
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Icon(
                        imageVector = if (showAdvanced) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                        contentDescription = null
                    )
                    Spacer(modifier = Modifier.width(ToolkitTheme.spacing.small))
                    Text(
                        text = if (showAdvanced) {
                            stringResource(Res.string.action_hide_advanced)
                        } else {
                            stringResource(Res.string.action_show_advanced)
                        }
                    )
                }

                AnimatedVisibility(
                    visible = showAdvanced,
                    enter = fadeIn() + expandVertically(),
                    exit = fadeOut() + shrinkVertically()
                ) {
                    Column(modifier = Modifier.padding(top = ToolkitTheme.spacing.medium)) {
                        val advStandard = advancedParams.filter { it.metadata.role == ParameterRole.STANDARD }
                        val advInputLoc = advancedParams.filter { it.metadata.role == ParameterRole.INPUT_LOCATION }
                        val advOutputLoc = advancedParams.filter { it.metadata.role == ParameterRole.OUTPUT_LOCATION }

                        if (advStandard.isNotEmpty()) {
                            ParameterGroup(
                                title = stringResource(Res.string.advanced_parameters_section),
                                parameters = advStandard,
                                providedSettings = providedSettings,
                                providedLocks = providedLocks,
                                hasUnsavedChanges = hasUnsavedChanges,
                                pluginId = pluginId,
                                onNavigateToPluginSetting = onNavigateToPluginSetting
                            )
                        }

                        if (advInputLoc.isNotEmpty()) {
                            ParameterGroup(
                                title = stringResource(Res.string.plugin_input_locations),
                                parameters = advInputLoc,
                                providedSettings = providedSettings,
                                providedLocks = providedLocks,
                                hasUnsavedChanges = hasUnsavedChanges,
                                pluginId = pluginId,
                                onNavigateToPluginSetting = onNavigateToPluginSetting
                            )
                        }

                        if (advOutputLoc.isNotEmpty()) {
                            ParameterGroup(
                                title = stringResource(Res.string.plugin_output_locations),
                                parameters = advOutputLoc,
                                providedSettings = providedSettings,
                                providedLocks = providedLocks,
                                hasUnsavedChanges = hasUnsavedChanges,
                                pluginId = pluginId,
                                onNavigateToPluginSetting = onNavigateToPluginSetting
                            )
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun ParameterGroup(
    title: String,
    parameters: List<ExecutionParameter>,
    providedSettings: Map<String, JsonElement> = emptyMap(),
    providedLocks: Map<String, Boolean> = emptyMap(),
    hasUnsavedChanges: Boolean = false,
    pluginId: String = "",
    onNavigateToPluginSetting: ((pluginId: String, settingKey: String) -> Unit)? = null
) {
    Text(
        title,
        style = MaterialTheme.typography.titleMedium,
        fontWeight = FontWeight.Bold,
        color = MaterialTheme.colorScheme.primary,
        modifier = Modifier.padding(vertical = ToolkitTheme.spacing.small)
    )
    Surface(
        modifier = Modifier.fillMaxWidth(),
        color = MaterialTheme.colorScheme.surface,
        shape = ToolkitTheme.shapes.small,
        border = BorderStroke(ToolkitTheme.dimensions.borderUnselected, MaterialTheme.colorScheme.outlineVariant)
    ) {
        Column(
            modifier = Modifier.padding(ToolkitTheme.spacing.medium),
            verticalArrangement = Arrangement.spacedBy(ToolkitTheme.spacing.medium)
        ) {
            parameters.forEach { param ->
                DynamicParameterInput(
                    name = param.name,
                    metadata = param.metadata,
                    value = param.value,
                    onValueChange = param.onValueChange,
                    enabled = param.enabled,
                    isAutoGenerated = param.isAutoGenerated,
                    providedSettings = providedSettings,
                    providedLocks = providedLocks,
                    hasUnsavedChanges = hasUnsavedChanges,
                    pluginId = param.pluginId.ifBlank { pluginId },
                    onNavigateToPluginSetting = onNavigateToPluginSetting
                )
            }
        }
    }
    Spacer(modifier = Modifier.height(ToolkitTheme.spacing.medium))
}
