package org.wip.plugintoolkit.features.plugin.viewmodel

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import co.touchlab.kermit.Logger
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.serialization.json.JsonPrimitive
import org.wip.plugintoolkit.api.Capability
import org.wip.plugintoolkit.api.PluginEntry
import org.wip.plugintoolkit.api.PluginManifest
import org.wip.plugintoolkit.core.model.localized
import org.wip.plugintoolkit.core.model.resolveNonComposable
import org.wip.plugintoolkit.core.notification.NotificationService
import org.wip.plugintoolkit.features.job.logic.JobManager
import org.wip.plugintoolkit.features.job.model.BackgroundJob
import org.wip.plugintoolkit.features.job.model.JobStatus
import org.wip.plugintoolkit.features.job.model.JobType
import org.wip.plugintoolkit.features.plugin.logic.PluginManager
import org.wip.plugintoolkit.features.plugin.utils.SettingsUtils
import plugintoolkit.composeapp.generated.resources.Res
import plugintoolkit.composeapp.generated.resources.capability_defaults_saved

/**
 * Dedicated ViewModel for hosting a single plugin in standalone execution mode.
 * Operates independently of multi-plugin collections, repository marketplace, and flow editor.
 */
class SinglePluginHostViewModel(
    val pluginEntry: PluginEntry,
    private val jobManager: JobManager,
    private val notificationService: NotificationService,
    private val pluginManager: PluginManager
) : ViewModel() {

    val manifest: PluginManifest = pluginEntry.getManifest().getOrThrow()
    val pluginId: String = manifest.plugin.id
    val capabilities: List<Capability> = manifest.capabilities
    val hasSetupHandler: Boolean = manifest.hasSetupHandler

    var selectedCapability by mutableStateOf<Capability?>(capabilities.firstOrNull())
    var saveResults by mutableStateOf(true)

    val parameterValues = mutableStateMapOf<String, String>()
    val manuallyModifiedParameters = mutableStateMapOf<String, Boolean>()

    val activeJobs = jobManager.jobs
    val endedJobs = jobManager.endedJobs
    val jobProgress = jobManager.jobProgress
    val jobLogs = jobManager.jobLogs

    val pluginLocksState = pluginManager.pluginLocksState
    val pluginSettingsState = pluginManager.pluginSettingsState

    private val jobCounterMutex = Mutex()
    private var jobCounter = 0

    val isSetupRunning: StateFlow<Boolean> = jobManager.jobs.combine(jobManager.endedJobs) { active, _ ->
        active.any { it.pluginId == pluginId && it.type == JobType.Setup && (it.status == JobStatus.Running || it.status == JobStatus.Queued) }
    }.stateIn(viewModelScope, SharingStarted.Eagerly, false)

    val isSetupCompleted: StateFlow<Boolean> = combine(
        pluginManager.installedPlugins,
        jobManager.endedJobs
    ) { installed, ended ->
        val installedRecord = installed.find { it.pkg == pluginId }
        val recordCompleted = installedRecord?.isSetupCompleted == true
        val jobCompleted = ended.any { it.pluginId == pluginId && it.type == JobType.Setup && it.status == JobStatus.Completed }
        recordCompleted || jobCompleted
    }.stateIn(viewModelScope, SharingStarted.Eagerly, false)

    val isPluginReady: StateFlow<Boolean> = combine(
        isSetupCompleted,
        isSetupRunning
    ) { completed, running ->
        if (hasSetupHandler) {
            completed && !running
        } else {
            !running
        }
    }.stateIn(viewModelScope, SharingStarted.Eagerly, !hasSetupHandler)

    init {
        selectedCapability?.let { selectCapability(it) }
        viewModelScope.launch {
            pluginManager.refreshLocks(pluginId)
        }
    }

    fun selectCapability(capability: Capability?) {
        selectedCapability = capability
        parameterValues.clear()
        manuallyModifiedParameters.clear()

        val store = pluginManager.loadPluginSettings(pluginId)

        capability?.parameters?.forEach { (name, meta) ->
            val userValue = store.capabilityParams[capability.name]?.get(name)
                ?: store.globalParams[name]
                ?: meta.defaultValue

            val rawString = userValue?.let {
                SettingsUtils.jsonToString(it, meta.type)
            }
            parameterValues[name] = SettingsUtils.resolveEffectiveValue(rawString, meta.defaultValue, meta.type)
        }
        recomputeAutogeneratedParameters()
    }

    fun updateParameter(name: String, value: String) {
        parameterValues[name] = value

        val capability = selectedCapability
        val isAutoGenerated = capability?.parameters?.get(name)?.autogeneratedPattern != null
        if (value.isEmpty() && isAutoGenerated) {
            manuallyModifiedParameters.remove(name)
        } else {
            manuallyModifiedParameters[name] = true
        }
        recomputeAutogeneratedParameters()
    }

    fun isParameterAutoGenerated(name: String): Boolean {
        val meta = selectedCapability?.parameters?.get(name) ?: return false
        return meta.autogeneratedPattern != null && !manuallyModifiedParameters.contains(name)
    }

    private fun recomputeAutogeneratedParameters() {
        val capability = selectedCapability ?: return
        val params = capability.parameters ?: return

        for ((outName, meta) in params) {
            val pattern = meta.autogeneratedPattern
            if (!pattern.isNullOrBlank()) {
                if (manuallyModifiedParameters.contains(outName)) {
                    continue
                }

                val pat = pattern ?: continue
                var resolvedPath: String = pat
                var canEvaluate = true
                val regex = Regex("\\{([^}]+)\\}")
                regex.findAll(pat).forEach { match ->
                    val depName = match.groupValues[1]
                    val depValue = parameterValues[depName]
                    if (!depValue.isNullOrEmpty()) {
                        resolvedPath = resolvedPath.replace(match.value, depValue)
                    } else {
                        canEvaluate = false
                    }
                }

                if (canEvaluate) {
                    parameterValues[outName] = normalizePath(resolvedPath)
                } else {
                    parameterValues[outName] = ""
                }
            }
        }
    }

    private fun normalizePath(path: String): String {
        val parts = path.replace("\\", "/").split("/")
        val resolved = mutableListOf<String>()
        for (part in parts) {
            if (part == "." || part.isEmpty()) continue
            if (part == "..") {
                if (resolved.isNotEmpty() && resolved.last() != "..") {
                    resolved.removeLast()
                } else {
                    resolved.add(part)
                }
            } else {
                resolved.add(part)
            }
        }
        val isAbsolute = path.startsWith("/") || path.matches(Regex("^[a-zA-Z]:[/\\\\].*"))
        val prefix = if (path.startsWith("/")) "/" else if (path.matches(Regex("^[a-zA-Z]:[/\\\\].*"))) path.substring(0, 3).replace("\\", "/") else ""
        val suffix = resolved.joinToString("/")
        return if (isAbsolute && !suffix.startsWith(prefix)) prefix + suffix else suffix
    }

    fun runSetup() {
        viewModelScope.launch {
            pluginManager.enqueueSetupJob(pluginId)
            notificationService.toast("Starting setup for ${manifest.plugin.name}...")
        }
    }

    fun executeCapability() {
        val capability = selectedCapability ?: return

        if (!isPluginReady.value) {
            val msg = if (hasSetupHandler && !isSetupCompleted.value) {
                "Plugin setup is required before executing capabilities"
            } else {
                "Plugin is not ready"
            }
            notificationService.toast(msg)
            return
        }

        viewModelScope.launch {
            val params = capability.parameters?.mapValues { (name, meta) ->
                val strVal = parameterValues[name] ?: ""
                SettingsUtils.stringToJson(strVal, meta.type)
            } ?: parameterValues.toMap().mapValues { (_, v) -> JsonPrimitive(v) }

            val jobId = jobCounterMutex.withLock { ++jobCounter }.toString()

            val job = BackgroundJob(
                id = jobId,
                name = "${manifest.plugin.name}: ${capability.name}",
                type = JobType.Capability,
                pluginId = pluginId,
                capabilityName = capability.name,
                parameters = params,
                keepResult = saveResults,
                isPausable = capability.isPausable,
                isCancellable = capability.isCancellable
            )
            jobManager.enqueueJob(job)

            notificationService.toast("Executing ${capability.name} in background")
        }
    }

    fun cancelJob(jobId: String, force: Boolean = false) {
        viewModelScope.launch {
            jobManager.cancelJob(jobId, force)
        }
    }

    fun pauseJob(jobId: String) {
        viewModelScope.launch {
            jobManager.pauseJob(jobId)
        }
    }

    fun resumeJob(jobId: String) {
        viewModelScope.launch {
            jobManager.resumeJob(jobId)
        }
    }

    fun removeEndedJob(jobId: String) {
        jobManager.clearEndedJob(jobId)
    }

    fun clearCapabilityHistory() {
        val capName = selectedCapability?.name ?: return
        jobManager.removeJobs {
            it.pluginId == pluginId &&
                it.capabilityName == capName &&
                (it.status == JobStatus.Completed || it.status == JobStatus.Failed || it.status == JobStatus.Cancelled)
        }
        jobManager.endedJobs.value.filter { it.pluginId == pluginId && it.capabilityName == capName }.forEach {
            jobManager.clearEndedJob(it.id)
        }
    }

    fun resetParametersToDefault() {
        val capability = selectedCapability ?: return
        selectCapability(capability)
    }

    fun saveCurrentParametersAsDefault() {
        val capability = selectedCapability ?: return
        val currentStore = pluginManager.loadPluginSettings(pluginId)
        val newParams = mutableMapOf<String, kotlinx.serialization.json.JsonElement>()
        capability.parameters?.forEach { (name, meta) ->
            val stringValue = parameterValues[name] ?: ""
            newParams[name] = SettingsUtils.stringToJson(stringValue, meta.type)
        }
        val updatedCapabilityParams = currentStore.capabilityParams.toMutableMap()
        updatedCapabilityParams[capability.name] = newParams
        val newStore = currentStore.copy(capabilityParams = updatedCapabilityParams)
        pluginManager.savePluginSettings(pluginId, newStore)

        notificationService.toast(
            message = Res.string.capability_defaults_saved.localized.resolveNonComposable(capability.name)
        )
    }
}
